import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";export const revalidate=0;
const domaines=[
{titre:"Soins infirmiers médico-chirurgicaux",description:"Révision structurée des principaux systèmes et pathologies de l’adulte.",modules:["Cardiovasculaire","Respiratoire","Neurologie","Gastro-intestinal","Rénal","Endocrinologie","Hématologie"]},
{titre:"Santé maternelle, obstétrique et néonatale",description:"Grossesse, travail, accouchement, postpartum et soins du nouveau-né.",modules:["Grossesse","Travail et accouchement","Postpartum","Nouveau-né"]},
{titre:"Soins infirmiers pédiatriques",description:"Croissance, développement et prise en charge des principales affections pédiatriques.",modules:["Croissance et développement","Nouveau-né","Maladies pédiatriques","Urgences pédiatriques"]},
{titre:"Pharmacologie",description:"Classes médicamenteuses, surveillance, sécurité et administration infirmière.",modules:["Principes de pharmacologie","Médicaments cardiovasculaires","Anti-infectieux","Analgésiques","Médicaments respiratoires","Endocrinologie et diabète","Gastro-intestinal et rénal","Neurologie et psychiatrie","Pharmacologie obstétricale","Médicaments d’urgence et antidotes","Vaccins et immunologie"]},
{titre:"Santé mentale et psychiatrie",description:"Troubles psychiatriques, communication thérapeutique, sécurité et interventions infirmières.",modules:["Évaluation psychiatrique","Troubles de l’humeur","Psychoses","Anxiété et stress","Troubles de la personnalité","Addictions et sevrage","Troubles neurocognitifs","Troubles alimentaires","Urgences psychiatriques","Psychiatrie de l’enfant et de l’adolescent","Éthique, droits et cadre légal"]},
{titre:"Santé communautaire et santé publique",description:"Prévention, épidémiologie, vaccination, maladies transmissibles, nutrition et suivi communautaire des maladies chroniques.",modules:["Prévention et promotion","Épidémiologie et surveillance","Santé familiale et soins à domicile","Éducation sanitaire et communication","Maladies transmissibles et environnement","Vaccination et chaîne du froid","VIH/SIDA et IST","Tuberculose en communauté","Nutrition communautaire","Maladies chroniques en communauté","Catastrophes et populations vulnérables"]},
{titre:"Fondements des soins infirmiers",description:"Principes essentiels, sécurité, hygiène et démarche de soins.",modules:["Démarche de soins","Sécurité du patient","Hygiène et infection","Soins de base"]},
{titre:"Urgences et soins critiques",description:"Priorités, stabilisation et surveillance du patient critique.",modules:["Évaluation ABCDE","État de choc","Urgences respiratoires","Urgences cardiovasculaires"]}];
const medico:Record<string,string>={Cardiovasculaire:"/cours-revisions/cardiovasculaire",Respiratoire:"/cours-revisions/respiratoire",Neurologie:"/cours-revisions/neurologie","Gastro-intestinal":"/cours-revisions/gastro-intestinal",Rénal:"/cours-revisions/renal",Endocrinologie:"/cours-revisions/endocrinologie",Hématologie:"/cours-revisions/hematologie"};
const maternite:Record<string,string>={Grossesse:"/cours-revisions/maternite/grossesse","Travail et accouchement":"/cours-revisions/maternite/travail-accouchement",Postpartum:"/cours-revisions/maternite/postpartum","Nouveau-né":"/cours-revisions/maternite/nouveau-ne"};
const pediatrie:Record<string,string>={"Croissance et développement":"/cours-revisions/pediatrie/croissance-developpement","Nouveau-né":"/cours-revisions/pediatrie/nouveau-ne","Maladies pédiatriques":"/cours-revisions/pediatrie/maladies-pediatriques","Urgences pédiatriques":"/cours-revisions/pediatrie/urgences-pediatriques"};
const pharmacologie:Record<string,string>={"Principes de pharmacologie":"/cours-revisions/pharmacologie/principes","Médicaments cardiovasculaires":"/cours-revisions/pharmacologie/cardiovasculaires","Anti-infectieux":"/cours-revisions/pharmacologie/anti-infectieux","Analgésiques":"/cours-revisions/pharmacologie/analgesiques","Médicaments respiratoires":"/cours-revisions/pharmacologie/respiratoire","Endocrinologie et diabète":"/cours-revisions/pharmacologie/endocrinologie","Gastro-intestinal et rénal":"/cours-revisions/pharmacologie/gastro-renal","Neurologie et psychiatrie":"/cours-revisions/pharmacologie/neuro-psy","Pharmacologie obstétricale":"/cours-revisions/pharmacologie/obstetrique","Médicaments d’urgence et antidotes":"/cours-revisions/pharmacologie/urgences-antidotes","Vaccins et immunologie":"/cours-revisions/pharmacologie/vaccins"};
const psy:Record<string,string>={"Évaluation psychiatrique":"/cours-revisions/sante-mentale/evaluation","Troubles de l’humeur":"/cours-revisions/sante-mentale/humeur",Psychoses:"/cours-revisions/sante-mentale/psychoses","Anxiété et stress":"/cours-revisions/sante-mentale/anxiete-stress","Troubles de la personnalité":"/cours-revisions/sante-mentale/personnalite","Addictions et sevrage":"/cours-revisions/sante-mentale/addictions","Troubles neurocognitifs":"/cours-revisions/sante-mentale/neurocognitifs","Troubles alimentaires":"/cours-revisions/sante-mentale/alimentaires","Urgences psychiatriques":"/cours-revisions/sante-mentale/urgences-psy","Psychiatrie de l’enfant et de l’adolescent":"/cours-revisions/sante-mentale/enfant-adolescent","Éthique, droits et cadre légal":"/cours-revisions/sante-mentale/ethique-legal"};
const communautaire:Record<string,string>={"Prévention et promotion":"/cours-revisions/sante-communautaire/prevention","Épidémiologie et surveillance":"/cours-revisions/sante-communautaire/epidemiologie","Santé familiale et soins à domicile":"/cours-revisions/sante-communautaire/famille","Éducation sanitaire et communication":"/cours-revisions/sante-communautaire/education","Maladies transmissibles et environnement":"/cours-revisions/sante-communautaire/infectieuses","Vaccination et chaîne du froid":"/cours-revisions/sante-communautaire/vaccination","VIH/SIDA et IST":"/cours-revisions/sante-communautaire/vih-ist","Tuberculose en communauté":"/cours-revisions/sante-communautaire/tuberculose","Nutrition communautaire":"/cours-revisions/sante-communautaire/nutrition","Maladies chroniques en communauté":"/cours-revisions/sante-communautaire/chroniques","Catastrophes et populations vulnérables":"/cours-revisions/sante-communautaire/catastrophes"};
export default async function Page(){const supabase=await createClient();const {data}=await supabase.auth.getClaims();if(!data?.claims?.sub)redirect("/connexion");return <main style={{maxWidth:1100,margin:"0 auto",padding:"28px 18px 90px"}}><section style={{background:"linear-gradient(135deg,#071b4f,#1748b7)",color:"white",borderRadius:22,padding:"28px 24px",marginBottom:24}}><div style={{fontSize:13,fontWeight:800,opacity:.8,textTransform:"uppercase",letterSpacing:1}}>Bibliothèque d’apprentissage</div><h1 style={{fontSize:32,margin:"8px 0"}}>Cours & Révisions</h1><p style={{maxWidth:720,lineHeight:1.65,margin:0,opacity:.92}}>Étudiez les notions essentielles des sciences infirmières grâce à des modules structurés, indépendants de la banque de questions et des examens.</p></section><div style={{display:"grid",gap:16}}>{domaines.map((d,index)=><section key={d.titre} style={{border:"1px solid #e3e9f3",borderRadius:18,background:"white",padding:20,boxShadow:"0 6px 22px rgba(11,31,89,.05)"}}><h2 style={{color:"#0b1f59",fontSize:20,margin:"0 0 7px"}}>{d.titre}</h2><p style={{color:"#64748b",lineHeight:1.55,margin:"0 0 16px"}}>{d.description}</p><div style={{display:"flex",flexWrap:"wrap",gap:9}}>{d.modules.map(m=>{const href=index===0?medico[m]:index===1?maternite[m]:index===2?pediatrie[m]:index===3?pharmacologie[m]:index===4?psy[m]:index===5?communautaire[m]:undefined;const theme=index===1?["#fff1f6","#a61e59","#f4c7da"]:index===2?["#ecfdf5","#06735a","#a7f3d0"]:index===3?["#fffbeb","#a16207","#fde68a"]:index===4?["#f5f3ff","#6d28d9","#ddd6fe"]:index===5?["#ecfdf5","#047857","#a7f3d0"]:["#eaf2ff","#1657d8","#bfd3ff"];return href?<a key={m} href={href} style={{background:theme[0],color:theme[1],border:`1px solid ${theme[2]}`,padding:"9px 13px",borderRadius:999,fontWeight:800,fontSize:13}}>{m} →</a>:<span key={m} style={{background:"#f5f7fb",color:"#64748b",border:"1px solid #e5eaf2",padding:"9px 13px",borderRadius:999,fontWeight:700,fontSize:13}}>{m}</span>})}</div></section>)}</div></main>}
