export type DoseExample = { title: string; given: string; steps: string[]; result: string; safety: string };
export const doseExamples: Record<string, DoseExample> = {
  "fiche-073": { title: "Pousse-seringue : volume et durée", given: "Exercice : 30 mL doivent passer en 6 heures.", steps: ["Débit = volume ÷ durée.", "30 mL ÷ 6 h = 5 mL/h."], result: "5 mL/h", safety: "Vérifier aussi la concentration, la dose prescrite et la programmation de la pompe." },
  "fiche-074": { title: "Repérer une erreur d’un facteur dix", given: "Prescription fictive : 50 mg. Solution : 100 mg dans 2 mL. Un calcul propose 10 mL.", steps: ["Concentration : 100 mg ÷ 2 mL = 50 mg/mL.", "Volume attendu : 50 mg ÷ 50 mg/mL = 1 mL.", "10 mL contiendraient 500 mg : dix fois la dose demandée."], result: "1 mL ; le résultat de 10 mL est incorrect", safety: "Ne pas administrer en cas de discordance : suspendre la préparation et faire clarifier." },
  "fiche-474": { title: "Convertir avant de calculer", given: "Exercice : convertir 0,5 g en mg, puis 250 microgrammes en mg.", steps: ["1 g = 1 000 mg : 0,5 × 1 000 = 500 mg.", "1 mg = 1 000 microgrammes : 250 ÷ 1 000 = 0,25 mg."], result: "500 mg et 0,25 mg", safety: "Toujours écrire le zéro avant la virgule : 0,25 mg, jamais ,25 mg." },
  "fiche-475": { title: "Comprimés : règle de trois", given: "Prescription fictive : 500 mg. Un comprimé contient 250 mg.", steps: ["Nombre = dose prescrite ÷ dose par comprimé.", "500 mg ÷ 250 mg/comprimé = 2 comprimés."], result: "2 comprimés", safety: "Vérifier la formulation et la voie. Une division de comprimé n’est possible que si elle est autorisée." },
  "fiche-476": { title: "Trouver le volume en mL", given: "Prescription fictive : 150 mg. Solution disponible : 100 mg dans 5 mL.", steps: ["Concentration : 100 ÷ 5 = 20 mg/mL.", "Volume : 150 mg ÷ 20 mg/mL = 7,5 mL."], result: "7,5 mL", safety: "Choisir un dispositif de mesure adapté à la voie ; ne pas utiliser une cuillère domestique." },
  "fiche-477": { title: "Distinguer par jour et par prise", given: "Prescription fictive : 30 mg/kg/jour en 3 prises égales. Poids : 20 kg.", steps: ["Dose quotidienne : 30 mg/kg/jour × 20 kg = 600 mg/jour.", "Dose par prise : 600 mg ÷ 3 = 200 mg."], result: "200 mg par prise, 3 prises par jour", safety: "Vérifier le poids récent en kg, la dose maximale et la prescription. mg/kg/jour n’est pas mg/kg/prise." },
  "fiche-478": { title: "Dose par surface corporelle", given: "Prescription fictive : 50 mg/m². Surface corporelle déjà calculée et validée : 1,6 m².", steps: ["Dose = dose par m² × surface corporelle.", "50 mg/m² × 1,6 m² = 80 mg."], result: "80 mg", safety: "La surface corporelle doit être validée ; vérifier le protocole et les éventuels plafonds ou adaptations." },
  "fiche-479": { title: "Utiliser la concentration après reconstitution", given: "La notice de cet exercice indique : après reconstitution, 1 000 mg dans un volume final de 10 mL. Dose fictive : 250 mg.", steps: ["Concentration finale : 1 000 ÷ 10 = 100 mg/mL.", "Volume à prélever : 250 ÷ 100 = 2,5 mL."], result: "2,5 mL", safety: "Le volume final n’est pas forcément le volume de diluant ajouté. Suivre la notice : diluant, stabilité et conservation." },
  "fiche-480": { title: "Dilution : volume final", given: "Exercice : préparer 20 mL à 5 mg/mL à partir d’une solution à 10 mg/mL.", steps: ["C₁ × V₁ = C₂ × V₂.", "V₁ = (5 mg/mL × 20 mL) ÷ 10 mg/mL = 10 mL.", "Prélever 10 mL de solution mère et compléter au volume final de 20 mL avec le diluant compatible."], result: "10 mL de solution mère, complétés à 20 mL", safety: "Vérifier compatibilité, concentration autorisée et asepsie. Ne pas ajouter 20 mL de diluant." },
  "fiche-481": { title: "Perfusion en mL/h", given: "Exercice : 500 mL en 4 heures.", steps: ["Débit = volume ÷ durée en heures.", "500 mL ÷ 4 h = 125 mL/h."], result: "125 mL/h", safety: "Vérifier le volume prescrit, l’état du patient et le réglage de la pompe." },
  "fiche-482": { title: "Perfusion par gravité", given: "Exercice : 500 mL en 4 heures. Tubulure indiquant 20 gouttes/mL.", steps: ["Durée : 4 × 60 = 240 minutes.", "Débit = (500 mL × 20 gouttes/mL) ÷ 240 min.", "10 000 ÷ 240 = 41,67 gouttes/min ; arrondir à la goutte entière."], result: "42 gouttes/min", safety: "Lire le facteur réel sur la tubulure et contrôler régulièrement le débit." },
  "fiche-483": { title: "Combien de temps dure la perfusion ?", given: "Exercice : 750 mL à 125 mL/h, sans interruption.", steps: ["Durée = volume ÷ débit.", "750 mL ÷ 125 mL/h = 6 h."], result: "6 heures", safety: "Une interruption change l’heure de fin. Ne pas accélérer pour rattraper sans prescription." },
  "fiche-484": { title: "Insuline : unités et concentration", given: "Exercice théorique : dose prescrite de 8 unités ; flacon U-100, soit 100 unités/mL.", steps: ["Équivalence mathématique : 8 unités ÷ 100 unités/mL = 0,08 mL.", "Avec une seringue à insuline U-100 adaptée, la graduation est 8 unités."], result: "8 unités sur le dispositif adapté U-100", safety: "Ne pas transposer à une autre concentration. Ne pas prélever dans un stylo avec une seringue. Vérifier glycémie, type d’insuline et prescription ; double contrôle selon protocole." },
  "fiche-485": { title: "Héparine : unités par heure", given: "Exercice fictif : 1 000 unités/h. Préparation validée : 25 000 unités dans un volume final de 250 mL.", steps: ["Concentration : 25 000 ÷ 250 = 100 unités/mL.", "Débit : 1 000 unités/h ÷ 100 unités/mL = 10 mL/h."], result: "10 mL/h", safety: "Médicament à haut risque : prescription, bilans, saignements et double contrôle selon protocole. Ce calcul ne définit pas une dose thérapeutique." },
  "fiche-486": { title: "Vasoactif : microgrammes/kg/min vers mL/h", given: "Exercice fictif : 0,1 microgramme/kg/min pour 60 kg. Concentration finale validée : 100 microgrammes/mL.", steps: ["0,1 microgramme/kg/min × 60 kg = 6 microgrammes/min.", "6 × 60 = 360 microgrammes/h.", "360 microgrammes/h ÷ 100 microgrammes/mL = 3,6 mL/h."], result: "3,6 mL/h", safety: "Aucune dose clinique n’est recommandée ici. Administration sur pompe avec surveillance continue, prescription et protocole spécifiques ; double contrôle selon protocole." },
};

export type StudyDiagram = { title: string; nodes: string[]; caption: string; source: string };
const endocrine = "https://www.ncbi.nlm.nih.gov/books/NBK613062/";
const asthma: StudyDiagram = { title: "Asthme : pourquoi l’air circule moins bien", nodes: ["Inflammation des voies aériennes", "Contraction musculaire et mucus", "Passage de l’air rétréci", "Expiration difficile, sifflements possibles"], caption: "Mécanisme simplifié : les signes varient et ne suffisent pas à mesurer la gravité d’une crise.", source: "https://www.ncbi.nlm.nih.gov/books/NBK613070/" };
export const studyDiagrams: Record<string, StudyDiagram> = {
  "fiche-027": asthma,
  "fiche-045": asthma,
  "fiche-001": { title: "Diabète de type 1 : manque d’insuline", nodes: ["Destruction des cellules bêta", "Production d’insuline très faible", "Utilisation du glucose perturbée", "Glucose élevé dans le sang"], caption: "Schéma simplifié. Une carence importante en insuline peut aussi entraîner une production de cétones.", source: endocrine },
  "fiche-197": { title: "Diabète de type 2 : réponse à l’insuline", nodes: ["Résistance à l’insuline", "Compensation initiale du pancréas", "Sécrétion devenue insuffisante", "Hyperglycémie persistante"], caption: "Évolution simplifiée et variable selon les personnes ; ce n’est pas une séquence identique pour tous.", source: endocrine },
  "fiche-018": { title: "Insuffisance cardiaque : deux conséquences", nodes: ["Remplissage ou éjection du cœur altéré", "Débit insuffisant et/ou pressions élevées", "Fatigue ou accumulation de liquide", "Dyspnée et/ou œdèmes possibles"], caption: "Schéma fonctionnel, non anatomique. Les manifestations dépendent notamment du côté du cœur atteint.", source: "https://www.ncbi.nlm.nih.gov/books/NBK613064/" },
};
