export type RubriquePathologie = {
  nom: string;
  definition: string;
  physiopathologie: string;
  risques: string;
  manifestations: string;
  examens: string;
  traitement: string;
  soins: string;
  complications: string;
  education: string;
  points: string;
  priorite: string;
};

export type SystemeCours = {
  slug: string;
  titre: string;
  rappel: string[];
  objectifs: string;
  pathologies: RubriquePathologie[];
  references: { label: string; href: string }[];
};

const commun = {
  education: "Expliquer la maladie avec des mots simples, renforcer l’adhésion au traitement, l’autosurveillance utile, les mesures de prévention et les signes d’alarme nécessitant une consultation rapide. Adapter l’enseignement aux capacités, au contexte familial et aux ressources du patient.",
};

export const autresSystemes: SystemeCours[] = [
  {
    slug: "respiratoire",
    titre: "Système respiratoire",
    objectifs: "Comprendre la ventilation et les échanges gazeux, reconnaître les principales pathologies respiratoires, identifier les signes de détresse, interpréter les examens courants et planifier des soins infirmiers sûrs et prioritaires.",
    rappel: [
      "Les voies aériennes conduisent l’air jusqu’aux alvéoles, où l’oxygène diffuse vers le sang et le dioxyde de carbone diffuse en sens inverse.",
      "La ventilation dépend du diaphragme, des muscles respiratoires, de la perméabilité des voies aériennes et du contrôle neurologique de la respiration.",
      "Une altération de la ventilation, de la diffusion ou de la perfusion pulmonaire peut provoquer hypoxémie, hypercapnie et détresse respiratoire.",
    ],
    pathologies: [
      {
        nom: "Asthme",
        definition: "Maladie inflammatoire chronique des voies aériennes caractérisée par une obstruction bronchique variable, souvent réversible, et une hyperréactivité bronchique.",
        physiopathologie: "L’exposition à un déclencheur active l’inflammation bronchique, l’œdème de la muqueuse, l’hypersécrétion de mucus et la bronchoconstriction. L’expiration devient plus difficile, ce qui peut entraîner piégeage d’air et augmentation du travail respiratoire.",
        risques: "Terrain atopique, antécédents familiaux, allergènes, fumée, infections virales, pollution, exercice, air froid et certains médicaments chez des patients sensibles.",
        manifestations: "Dyspnée, sibilants, toux, oppression thoracique, expiration prolongée et symptômes variables dans le temps. Un silence auscultatoire avec détresse importante est un signe de gravité.",
        examens: "Spirométrie avec recherche de variabilité ou réversibilité de l’obstruction; débit expiratoire de pointe pour certains patients; saturation et gaz du sang en exacerbation sévère.",
        traitement: "Bronchodilatateurs inhalés pour le soulagement selon le plan thérapeutique et traitement anti-inflammatoire de fond principalement par corticostéroïdes inhalés; prise en charge urgente des exacerbations sévères avec oxygène si hypoxémie et traitements protocolisés.",
        soins: "Évaluer fréquence respiratoire, parole, tirage, sibilants, saturation et réponse au traitement. Installer en position facilitant la respiration, administrer les traitements prescrits, vérifier la technique d’inhalation et surveiller l’épuisement respiratoire.",
        complications: "État de mal asthmatique, hypoxémie sévère, hypercapnie, insuffisance respiratoire et arrêt respiratoire.",
        education: commun.education + " Identifier les déclencheurs, maîtriser la technique de l’inhalateur et suivre le plan d’action écrit si disponible.",
        points: "La sévérité se juge surtout sur l’état clinique et la réponse au traitement. Une diminution des sibilants n’est pas forcément rassurante si le débit d’air devient très faible.",
        priorite: "Devant une exacerbation sévère, prioriser ABC, positionnement, saturation, oxygène si indiqué, bronchodilatation rapide selon protocole et surveillance rapprochée. Un patient épuisé, confus, cyanotique ou avec silence auscultatoire nécessite une escalade urgente.",
      },
      {
        nom: "BPCO",
        definition: "Maladie respiratoire chronique avec limitation persistante du débit aérien, le plus souvent liée à une exposition prolongée à des particules ou gaz nocifs.",
        physiopathologie: "Inflammation chronique, destruction alvéolaire, perte du recul élastique et obstruction des petites voies aériennes réduisent les débits expiratoires et favorisent le piégeage d’air.",
        risques: "Tabagisme, fumées de biomasse, expositions professionnelles, pollution et plus rarement déficit en alpha-1 antitrypsine.",
        manifestations: "Dyspnée progressive, toux chronique, expectorations, diminution de la tolérance à l’effort, sibilants et exacerbations infectieuses ou non infectieuses.",
        examens: "Spirométrie après bronchodilatateur, saturation, radiographie selon le contexte, gaz du sang en décompensation et recherche de causes ou comorbidités.",
        traitement: "Arrêt du tabac, bronchodilatateurs inhalés, vaccination, réadaptation respiratoire et traitements supplémentaires selon le profil; oxygénothérapie au long cours pour certaines hypoxémies chroniques documentées.",
        soins: "Surveiller respiration, saturation, état mental, sécrétions et tolérance à l’activité. Favoriser respiration à lèvres pincées, économie d’énergie, hydratation adaptée et bonne technique des inhalateurs.",
        complications: "Exacerbation aiguë, pneumonie, insuffisance respiratoire, hypertension pulmonaire, cœur pulmonaire et dénutrition.",
        education: commun.education + " Insister sur l’arrêt du tabac, la vaccination, la reconnaissance précoce d’une exacerbation et l’utilisation correcte des inhalateurs.",
        points: "L’oxygène doit être titré selon la situation clinique et les prescriptions; il ne faut pas retarder l’oxygénation d’un patient hypoxémique par peur de la rétention de CO₂.",
        priorite: "Lors d’une exacerbation, évaluer rapidement le travail respiratoire, l’oxygénation et l’état mental; administrer les traitements prescrits et surveiller les signes d’épuisement ou d’hypercapnie nécessitant une assistance ventilatoire.",
      },
      {
        nom: "Pneumonie",
        definition: "Infection du parenchyme pulmonaire provoquant inflammation et remplissage alvéolaire, avec altération possible des échanges gazeux.",
        physiopathologie: "Les agents infectieux déclenchent une réponse inflammatoire locale; exsudat et cellules inflammatoires occupent les alvéoles, créant un déséquilibre ventilation-perfusion.",
        risques: "Âge extrême, maladie chronique, dysphagie, altération de conscience, immunodépression, tabagisme, hospitalisation et ventilation mécanique.",
        manifestations: "Fièvre, toux, expectoration, dyspnée, douleur thoracique pleurale, crépitants, tachypnée et parfois confusion chez la personne âgée.",
        examens: "Examen clinique, saturation, radiographie thoracique, hémogramme; cultures et examens microbiologiques selon la sévérité et le contexte.",
        traitement: "Antibiothérapie lorsqu’une cause bactérienne est probable ou documentée, oxygène si hypoxémie, hydratation et prise en charge des complications; antiviraux dans certaines infections spécifiques.",
        soins: "Surveiller respiration, saturation, température, état mental, hydratation et sécrétions. Favoriser mobilisation, toux efficace, exercices respiratoires et prélèvements avant antibiothérapie lorsque cela est indiqué sans retarder le traitement urgent.",
        complications: "Sepsis, insuffisance respiratoire, abcès pulmonaire, épanchement parapneumonique et empyème.",
        education: commun.education + " Renforcer vaccination appropriée, hygiène des mains et adhésion à la durée complète de l’antibiothérapie prescrite.",
        points: "Chez un patient fragile, une pneumonie peut se manifester surtout par confusion, faiblesse ou décompensation d’une maladie chronique.",
        priorite: "Rechercher immédiatement hypoxémie, détresse respiratoire, hypotension et altération de conscience. Ces signes peuvent indiquer une pneumonie sévère ou un sepsis et imposent une prise en charge rapide.",
      },
      {
        nom: "Embolie pulmonaire",
        definition: "Obstruction aiguë d’une ou plusieurs artères pulmonaires, le plus souvent par un thrombus provenant du réseau veineux profond.",
        physiopathologie: "L’obstruction augmente brutalement les résistances vasculaires pulmonaires, altère les échanges gazeux et peut surcharger le ventricule droit jusqu’au choc obstructif.",
        risques: "Immobilisation, chirurgie, cancer, grossesse/postpartum, thrombose antérieure, œstrogènes, traumatisme et thrombophilie.",
        manifestations: "Dyspnée brutale, douleur pleurale, tachycardie, tachypnée, hypoxémie, syncope ou hémoptysie; une EP massive peut provoquer hypotension et choc.",
        examens: "Évaluation de probabilité clinique, D-dimères dans certains profils, angioscanner pulmonaire, échographie veineuse et échocardiographie en cas d’instabilité selon le contexte.",
        traitement: "Anticoagulation si indiquée; thrombolyse, thrombectomie ou autres stratégies de reperfusion pour certains patients à haut risque ou instables.",
        soins: "Limiter l’effort, surveiller ECG, pression, respiration, saturation et signes de choc; administrer oxygène et anticoagulants prescrits; surveiller les saignements sous traitement.",
        complications: "Choc obstructif, arrêt cardiaque, récidive thromboembolique et hypertension pulmonaire thromboembolique chronique.",
        education: commun.education + " Enseigner la sécurité sous anticoagulant et la prévention de la stase veineuse.",
        points: "Une dyspnée soudaine inexpliquée avec douleur thoracique ou syncope doit faire évoquer une embolie pulmonaire, surtout en présence de facteurs de risque thromboemboliques.",
        priorite: "En cas de suspicion avec hypotension, syncope, détresse ou hypoxémie importante, traiter comme une urgence: ABC, oxygénation, monitorage, accès veineux et alerte immédiate pour stratégie de reperfusion si indiquée.",
      },
      {
        nom: "Pneumothorax",
        definition: "Présence d’air dans l’espace pleural provoquant une perte partielle ou totale de l’expansion pulmonaire.",
        physiopathologie: "L’entrée d’air annule la pression négative pleurale. Dans le pneumothorax sous tension, la pression augmente progressivement, déplace le médiastin, réduit le retour veineux et peut provoquer un choc obstructif.",
        risques: "Traumatisme thoracique, procédures invasives, ventilation mécanique, maladie pulmonaire et rupture spontanée de bulles sous-pleurales.",
        manifestations: "Douleur thoracique brutale, dyspnée, diminution des bruits respiratoires du côté atteint. Sous tension: détresse sévère, hypotension, tachycardie et signes de mauvaise perfusion.",
        examens: "Diagnostic clinique prioritaire si tension; échographie ou radiographie peuvent confirmer un pneumothorax chez le patient stable.",
        traitement: "Observation de certains petits pneumothorax stables; drainage pleural selon la taille et les symptômes; décompression urgente avant imagerie si pneumothorax sous tension suspecté.",
        soins: "Surveiller respiration, saturation, douleur et signes vitaux; maintenir le système de drainage selon protocole, vérifier connexions et pansement, et ne pas clamper un drain sans indication claire.",
        complications: "Pneumothorax sous tension, hypoxémie, récidive, infection du drainage et œdème de réexpansion.",
        education: commun.education + " Informer sur les signes de récidive et les restrictions temporaires telles que voyage aérien ou plongée selon avis spécialisé.",
        points: "Le pneumothorax sous tension est un diagnostic clinique et son traitement ne doit pas attendre une radiographie chez un patient instable.",
        priorite: "Devant détresse respiratoire aiguë, hypotension et bruits respiratoires très diminués unilatéralement, alerter immédiatement et préparer la décompression urgente selon protocole.",
      },
    ],
    references: [
      { label: "GINA — Global Strategy for Asthma Management and Prevention", href: "https://ginasthma.org/" },
      { label: "GOLD — Global Strategy for the Diagnosis, Management, and Prevention of COPD", href: "https://goldcopd.org/" },
      { label: "IDSA/ATS — Community-Acquired Pneumonia Guidance", href: "https://www.idsociety.org/practice-guideline/community-acquired-pneumonia-cap-in-adults/" },
      { label: "ESC — Acute Pulmonary Embolism Guidelines", href: "https://www.escardio.org/Guidelines/Clinical-Practice-Guidelines/Acute-Pulmonary-Embolism-Diagnosis-and-Management-of" },
    ],
  },
  {
    slug: "neurologie",
    titre: "Système neurologique",
    objectifs: "Comprendre les fonctions neurologiques essentielles, reconnaître rapidement les urgences cérébrales et planifier des soins centrés sur la sécurité, la perfusion cérébrale, les voies aériennes et la prévention des complications.",
    rappel: [
      "Le système nerveux central comprend cerveau et moelle épinière; le système périphérique relie ces structures aux muscles, organes et récepteurs sensoriels.",
      "La fonction neurologique dépend d’un apport continu en oxygène et glucose et d’une pression de perfusion cérébrale suffisante.",
      "Toute altération aiguë de conscience, langage, force, pupilles ou convulsions prolongées peut traduire une urgence neurologique.",
    ],
    pathologies: [
      {
        nom: "Accident vasculaire cérébral",
        definition: "Déficit neurologique aigu dû à une interruption du flux sanguin cérébral par occlusion artérielle ou rupture vasculaire.",
        physiopathologie: "Dans l’AVC ischémique, un thrombus ou embole prive une zone cérébrale d’oxygène. Dans l’AVC hémorragique, le saignement détruit le tissu et peut augmenter la pression intracrânienne.",
        risques: "Hypertension, fibrillation auriculaire, diabète, tabagisme, dyslipidémie, âge, maladie vasculaire et antécédent d’AIT/AVC.",
        manifestations: "Faiblesse ou engourdissement unilatéral, asymétrie faciale, trouble de la parole, perte visuelle, ataxie ou déficit soudain. Céphalée brutale peut suggérer une hémorragie.",
        examens: "Évaluation neurologique immédiate, glycémie, scanner cérébral sans contraste en urgence, angio-imagerie selon protocole, ECG et bilans complémentaires.",
        traitement: "Reperfusion de certains AVC ischémiques par thrombolyse IV et/ou thrombectomie mécanique selon critères et délais; prise en charge spécifique des hémorragies et contrôle des complications.",
        soins: "Noter précisément l’heure de début ou dernière fois vu normal, maintenir ABC, vérifier glycémie, garder NPO jusqu’au dépistage de déglutition, surveiller état neurologique et prévention des complications d’immobilité.",
        complications: "Œdème cérébral, aspiration, pneumonie, TVP, crises, chute, dépression, récidive et handicap.",
        education: commun.education + " Enseigner les signes FAST et l’importance d’appeler immédiatement les services d’urgence.",
        points: "Le temps est critique. Un déficit soudain doit être évalué comme un AVC jusqu’à preuve du contraire.",
        priorite: "Déclencher immédiatement la filière AVC: ABC, heure de début, glycémie, examen neurologique et imagerie urgente. Ne rien donner par voie orale avant évaluation de la déglutition.",
      },
      {
        nom: "Crise épileptique et état de mal",
        definition: "Décharge électrique neuronale anormale provoquant manifestations motrices, sensitives, autonomes ou altération de conscience; l’état de mal est une urgence lorsque les crises se prolongent ou se répètent sans récupération adéquate.",
        physiopathologie: "Un déséquilibre entre excitation et inhibition neuronales produit une activité hypersynchrone. Une activité prolongée augmente besoins métaboliques et risque de lésion systémique et cérébrale.",
        risques: "Épilepsie connue, arrêt de traitement, AVC, tumeur, infection, traumatisme, troubles métaboliques, sevrage alcoolique et toxiques.",
        manifestations: "Convulsions généralisées ou focales, regard fixe, automatismes, perte de conscience et phase post-critique; état de mal si absence de récupération ou durée anormalement prolongée.",
        examens: "Glycémie et causes réversibles en urgence, électrolytes, imagerie selon contexte et EEG pour classification ou état de mal non convulsif.",
        traitement: "Protection des voies aériennes et benzodiazépine de première intention pour état de mal selon protocole, suivie d’antiépileptiques adaptés et traitement de la cause.",
        soins: "Protéger des blessures, ne rien mettre dans la bouche, ne pas retenir les mouvements, chronométrer la crise, placer latéralement après convulsions si possible et réévaluer respiration et conscience.",
        complications: "Hypoxie, aspiration, traumatisme, acidose, hyperthermie, rhabdomyolyse et lésion cérébrale lors d’un état de mal prolongé.",
        education: commun.education + " Enseigner sécurité, observance et conduite à tenir aux proches.",
        points: "La durée de la crise et la récupération entre les épisodes sont des informations essentielles.",
        priorite: "Pendant une crise, protéger le patient et maintenir les voies aériennes; si elle se prolonge ou se répète sans récupération, traiter comme un état de mal et activer immédiatement le protocole d’urgence.",
      },
      {
        nom: "Méningite",
        definition: "Inflammation des méninges, souvent infectieuse, pouvant évoluer rapidement vers sepsis, atteinte neurologique et décès.",
        physiopathologie: "L’agent infectieux déclenche une inflammation méningée qui augmente perméabilité vasculaire, œdème et parfois pression intracrânienne.",
        risques: "Âge extrême, immunodépression, vie en collectivité, absence de vaccination, fuite de LCR et certaines infections ORL.",
        manifestations: "Fièvre, céphalée, raideur de nuque, photophobie, vomissements, altération de conscience; pétéchies/purpura peuvent accompagner certaines infections méningococciques.",
        examens: "Hémocultures, ponction lombaire lorsque sûre, analyse du LCR et imagerie cérébrale avant PL dans certains contextes à risque.",
        traitement: "Antibiothérapie empirique urgente pour suspicion bactérienne, parfois dexaméthasone selon protocole, puis adaptation aux résultats; isolement gouttelettes selon agent suspecté.",
        soins: "Mettre en place précautions appropriées, surveiller conscience, pupilles, crises, signes vitaux et perfusion; réduire stimulations si photophobie et préparer prélèvements sans retarder les antibiotiques urgents.",
        complications: "Sepsis, choc, œdème cérébral, convulsions, surdité, déficit neurologique et décès.",
        education: commun.education + " Expliquer prophylaxie des contacts lorsque indiquée et vaccination.",
        points: "Une suspicion de méningite bactérienne est une urgence thérapeutique.",
        priorite: "Devant fièvre avec raideur de nuque et altération neurologique, initier précautions, ABC, surveillance et alerte médicale urgente afin de ne pas retarder l’antibiothérapie.",
      },
      {
        nom: "Hypertension intracrânienne",
        definition: "Augmentation pathologique de la pression à l’intérieur du crâne pouvant compromettre la perfusion cérébrale et provoquer une herniation.",
        physiopathologie: "Le volume intracrânien est partagé entre cerveau, sang et LCR. Une augmentation d’un compartiment non compensée élève la pression et réduit la perfusion cérébrale.",
        risques: "Traumatisme, tumeur, hémorragie, œdème, hydrocéphalie, infection et AVC massif.",
        manifestations: "Céphalée, vomissements, baisse de conscience, anomalies pupillaires; bradycardie avec hypertension et respiration irrégulière sont des signes tardifs graves.",
        examens: "Examen neurologique répété, imagerie cérébrale et monitorage invasif de la pression dans certains patients critiques.",
        traitement: "Traitement de la cause, optimisation ventilation/perfusion, tête surélevée, osmothérapie ou drainage du LCR selon indication et neurochirurgie si nécessaire.",
        soins: "Maintenir tête et cou en position neutre, éviter Valsalva et flexions extrêmes, surveiller neurologie, pupilles, respiration et hémodynamique; limiter interventions qui augmentent la pression.",
        complications: "Herniation cérébrale, ischémie, arrêt respiratoire et décès.",
        education: commun.education,
        points: "Une baisse progressive de conscience est souvent un signe plus sensible que les signes tardifs de Cushing.",
        priorite: "Toute détérioration de conscience ou nouvelle anisocorie impose une réévaluation immédiate des ABC, une alerte urgente et des mesures de protection de la perfusion cérébrale.",
      },
      {
        nom: "Maladie de Parkinson",
        definition: "Maladie neurodégénérative progressive dominée par bradykinésie associée à rigidité, tremblement de repos et troubles posturaux.",
        physiopathologie: "La perte de neurones dopaminergiques de la substance noire perturbe les circuits des ganglions de la base et le contrôle du mouvement.",
        risques: "Âge, susceptibilité génétique et certaines expositions; la majorité des cas sont multifactoriels.",
        manifestations: "Bradykinésie, rigidité, tremblement, marche à petits pas, instabilité, dysarthrie, dysphagie, constipation, troubles du sommeil et symptômes non moteurs.",
        examens: "Diagnostic principalement clinique; imagerie ou examens complémentaires servent surtout à exclure d’autres causes.",
        traitement: "Lévodopa/carbidopa et autres traitements dopaminergiques selon symptômes; rééducation, activité physique et prise en charge multidisciplinaire.",
        soins: "Respecter strictement les horaires des médicaments, prévenir chutes, évaluer déglutition et nutrition, favoriser mobilité et autonomie, surveiller hypotension orthostatique et confusion.",
        complications: "Chutes, aspiration, pneumonie, fluctuations motrices, dyskinésies, démence et dysautonomie.",
        education: commun.education + " Expliquer l’importance des horaires de médicaments et de l’exercice régulier.",
        points: "Le retard d’une dose peut entraîner une dégradation motrice importante chez certains patients hospitalisés.",
        priorite: "Sécuriser mobilité et déglutition et maintenir les médicaments dopaminergiques à l’horaire prescrit; toute dysphagie importante nécessite des précautions d’aspiration.",
      },
    ],
    references: [
      { label: "AHA/ASA — Guidelines for Acute Ischemic Stroke", href: "https://professional.heart.org/en/science-news/2019-update-to-the-2018-guidelines-for-the-early-management-of-acute-ischemic-stroke" },
      { label: "WHO — Epilepsy", href: "https://www.who.int/news-room/fact-sheets/detail/epilepsy" },
      { label: "WHO — Meningitis", href: "https://www.who.int/news-room/fact-sheets/detail/meningitis" },
    ],
  },
  {
    slug: "gastro-intestinal",
    titre: "Système gastro-intestinal",
    objectifs: "Reconnaître les principales affections digestives, différencier les urgences abdominales, surveiller hydratation, nutrition et saignement, et prévenir les complications postopératoires ou infectieuses.",
    rappel: [
      "Le tube digestif assure ingestion, digestion, absorption et élimination; foie, pancréas et voies biliaires participent à la digestion et au métabolisme.",
      "La perfusion intestinale, l’intégrité de la muqueuse et la motilité sont indispensables au fonctionnement digestif normal.",
      "Douleur abdominale aiguë, défense, hémorragie digestive, vomissements persistants ou signes de choc nécessitent une évaluation rapide.",
    ],
    pathologies: [
      {
        nom: "Hémorragie digestive",
        definition: "Saignement provenant du tube digestif, haut ou bas, pouvant aller d’une perte occulte à une hémorragie massive avec choc.",
        physiopathologie: "La rupture ou l’érosion d’un vaisseau digestif entraîne une perte sanguine; la baisse de volume circulant peut réduire la perfusion tissulaire et provoquer un choc hypovolémique.",
        risques: "Ulcère, varices œsophagiennes, AINS, anticoagulants, maladie hépatique, diverticulose et lésions tumorales.",
        manifestations: "Hématémèse, méléna, rectorragie, faiblesse, vertiges, tachycardie, hypotension, pâleur et syncope selon l’importance.",
        examens: "Hémogramme, coagulation, fonction rénale/hépatique, groupage et compatibilité, endoscopie et imagerie selon localisation et stabilité.",
        traitement: "Réanimation circulatoire, transfusion selon indication, traitement endoscopique ou interventionnel et traitement de la cause; médicaments spécifiques selon origine.",
        soins: "Évaluer ABC, quantifier les pertes, surveiller signes vitaux, perfusion, diurèse et état mental; établir accès veineux, préparer bilans/transfusion et maintenir NPO selon situation.",
        complications: "Choc hypovolémique, anémie sévère, ischémie myocardique et récidive hémorragique.",
        education: commun.education + " Éviter automédication par AINS si à risque et respecter surveillance sous anticoagulant.",
        points: "Une pression artérielle encore normale n’exclut pas une hémorragie importante si tachycardie et signes de mauvaise perfusion apparaissent.",
        priorite: "Devant saignement actif avec instabilité, prioriser ABC, deux accès veineux si possible, bilans urgents, monitorage et préparation à la réanimation/transfusion selon protocole.",
      },
      {
        nom: "Occlusion intestinale",
        definition: "Arrêt partiel ou complet du passage du contenu intestinal par obstacle mécanique ou paralysie fonctionnelle.",
        physiopathologie: "L’accumulation de gaz et liquides dilate l’intestin, augmente les pertes intraluminales et peut compromettre la perfusion, surtout en cas d’étranglement.",
        risques: "Adhérences postopératoires, hernie, tumeur, volvulus, fécalome et iléus après chirurgie ou maladie grave.",
        manifestations: "Douleur colique, distension, vomissements, arrêt des gaz/selles et bruits intestinaux variables; douleur continue avec défense peut suggérer ischémie.",
        examens: "Examen clinique, bilan biologique et scanner abdominal souvent déterminant; radiographie simple dans certains contextes.",
        traitement: "NPO, décompression nasogastrique selon indication, liquides IV et correction électrolytique; chirurgie urgente si strangulation, perforation ou obstacle non résolutif.",
        soins: "Surveiller douleur, abdomen, vomissements, aspiration NG, entrées/sorties, électrolytes et signes de péritonite. Ne pas administrer laxatifs sans évaluation si obstruction suspectée.",
        complications: "Ischémie, nécrose, perforation, péritonite, sepsis et choc.",
        education: commun.education,
        points: "L’aggravation de la douleur, fièvre, tachycardie et défense abdominale sont des signes d’alarme.",
        priorite: "Si douleur devient continue avec défense, fièvre ou instabilité, suspecter strangulation/perforation et alerter immédiatement; maintenir NPO et préparer prise en charge chirurgicale.",
      },
      {
        nom: "Pancréatite aiguë",
        definition: "Inflammation aiguë du pancréas liée à une activation prématurée des enzymes digestives, avec gravité très variable.",
        physiopathologie: "L’autodigestion enzymatique provoque inflammation locale, œdème et parfois nécrose; la réponse inflammatoire systémique peut entraîner défaillance d’organes.",
        risques: "Lithiase biliaire, alcool, hypertriglycéridémie, certains médicaments et procédures biliaires.",
        manifestations: "Douleur épigastrique intense irradiant au dos, nausées, vomissements, sensibilité abdominale, tachycardie et parfois hypotension.",
        examens: "Lipase, bilan hépatique et métabolique, échographie biliaire; scanner selon diagnostic incertain ou complications.",
        traitement: "Hydratation IV adaptée, analgésie, nutrition entérale précoce lorsque tolérée et traitement de la cause; antibiotiques non systématiques en pancréatite stérile.",
        soins: "Surveiller douleur, respiration, hémodynamique, diurèse, glycémie, électrolytes et tolérance nutritionnelle; repérer signes de défaillance d’organe.",
        complications: "Nécrose, infection, pseudokyste, insuffisance respiratoire, rénale, choc et sepsis.",
        education: commun.education + " Agir sur alcool, tabac et facteurs métaboliques selon la cause.",
        points: "La gravité dépend surtout de la défaillance d’organe et des complications, pas uniquement du niveau de lipase.",
        priorite: "Devant hypotension, hypoxémie ou oligurie, reconnaître une forme sévère et intensifier immédiatement surveillance, réanimation liquidienne et prise en charge multidisciplinaire.",
      },
      {
        nom: "Cirrhose",
        definition: "Fibrose hépatique avancée avec distorsion de l’architecture du foie, hypertension portale et insuffisance hépatocellulaire.",
        physiopathologie: "L’agression chronique entraîne inflammation, fibrose et nodules de régénération, augmentant la résistance au flux portal et réduisant les fonctions métaboliques/synthétiques du foie.",
        risques: "Alcool, hépatites virales, maladie métabolique associée au foie gras et autres maladies hépatiques chroniques.",
        manifestations: "Ascite, œdèmes, ictère, fatigue, prurit, ecchymoses, varices, splénomégalie et encéphalopathie.",
        examens: "Bilan hépatique, INR, albumine, numération, échographie et élastographie; endoscopie pour varices et surveillance du carcinome hépatocellulaire selon recommandations.",
        traitement: "Traitement de la cause, diurétiques et restriction sodée pour ascite, prise en charge de l’encéphalopathie, prévention/traitement des varices et transplantation pour maladie avancée sélectionnée.",
        soins: "Surveiller poids, périmètre abdominal, œdèmes, état mental, saignement, peau et nutrition; éviter médicaments hépatotoxiques non prescrits et surveiller réponse aux diurétiques.",
        complications: "Hémorragie variqueuse, péritonite bactérienne spontanée, encéphalopathie, syndrome hépatorénal et carcinome hépatocellulaire.",
        education: commun.education + " Éviter alcool et médicaments non validés, surveiller poids et signes de saignement/confusion.",
        points: "Une confusion nouvelle chez un patient cirrhotique doit faire rechercher rapidement une encéphalopathie et son facteur déclenchant.",
        priorite: "Hématémèse, confusion marquée, fièvre avec ascite ou hypotension sont des urgences potentielles et nécessitent une évaluation immédiate.",
      },
      {
        nom: "Maladie inflammatoire intestinale",
        definition: "Groupe de maladies inflammatoires chroniques comprenant principalement maladie de Crohn et rectocolite hémorragique.",
        physiopathologie: "Une réponse immunitaire dysrégulée chez un sujet prédisposé provoque inflammation chronique; Crohn peut atteindre toute l’épaisseur et tout le tube digestif, alors que la rectocolite touche le côlon de façon continue.",
        risques: "Prédisposition génétique, facteurs immunitaires et environnementaux; le tabac influence différemment Crohn et rectocolite.",
        manifestations: "Diarrhée chronique, douleurs abdominales, sang dans les selles surtout en rectocolite, perte de poids, fatigue et manifestations extra-intestinales.",
        examens: "Endoscopie avec biopsies, marqueurs inflammatoires, imagerie et analyses de selles pour exclure infection.",
        traitement: "Aminosalicylés dans certaines formes, corticostéroïdes pour poussées, immunomodulateurs et biothérapies; chirurgie selon complications ou maladie réfractaire.",
        soins: "Évaluer fréquence/sang des selles, douleur, poids, nutrition, hydratation, peau périnéale et effets des immunosuppresseurs.",
        complications: "Fistules, sténoses, abcès, mégacôlon toxique, hémorragie, malnutrition et risque accru de cancer colorectal selon durée/extension.",
        education: commun.education + " Encourager suivi régulier, nutrition individualisée et prévention infectieuse sous immunosuppression.",
        points: "Une poussée sévère avec distension, fièvre et tachycardie peut annoncer un mégacôlon toxique.",
        priorite: "Devant distension croissante, douleur, fièvre et signes systémiques, éviter antidiarrhéiques non prescrits et alerter rapidement pour exclure mégacôlon toxique ou perforation.",
      },
    ],
    references: [
      { label: "ACG — Clinical Guidelines", href: "https://gi.org/clinical-guidelines/" },
      { label: "AASLD — Practice Guidelines", href: "https://www.aasld.org/practice-guidelines" },
    ],
  },
  {
    slug: "renal",
    titre: "Système rénal",
    objectifs: "Comprendre filtration et équilibre hydro-électrolytique, reconnaître insuffisance rénale et infections urinaires compliquées, surveiller la dialyse et prévenir les désordres menaçant le pronostic vital.",
    rappel: [
      "Les reins filtrent le plasma, éliminent les déchets, régulent eau, sodium, potassium, équilibre acido-basique et participent au contrôle de la pression et de l’érythropoïèse.",
      "Une baisse du débit de filtration peut entraîner rétention hydrosodée, hyperkaliémie, acidose et accumulation de toxines.",
      "La tendance de la créatinine, la diurèse et l’état clinique sont souvent plus informatifs qu’une valeur isolée.",
    ],
    pathologies: [
      {
        nom: "Insuffisance rénale aiguë",
        definition: "Diminution rapide de la fonction rénale avec accumulation de déchets et perturbations hydro-électrolytiques, souvent potentiellement réversibles.",
        physiopathologie: "Elle peut être prérénale par hypoperfusion, intrinsèque par atteinte du parenchyme ou postrénale par obstruction.",
        risques: "Sepsis, déshydratation, choc, médicaments néphrotoxiques, contraste, obstruction urinaire et chirurgie majeure.",
        manifestations: "Oligurie parfois absente, œdèmes, dyspnée, nausées, confusion, faiblesse ou arythmies selon troubles électrolytiques.",
        examens: "Créatinine sériée, diurèse, électrolytes, analyse urinaire, échographie si obstruction possible et examens ciblés selon cause.",
        traitement: "Corriger cause et perfusion, arrêter néphrotoxiques si possible, gérer volumes/électrolytes; dialyse en cas d’indications graves réfractaires.",
        soins: "Mesurer entrées/sorties et poids, surveiller pression, œdèmes, poumons, potassium, créatinine et médicaments ajustés à la fonction rénale.",
        complications: "Hyperkaliémie, surcharge pulmonaire, acidose, urémie et troubles du rythme.",
        education: commun.education + " Éviter automédication néphrotoxique et maintenir suivi biologique.",
        points: "Une diurèse normale n’exclut pas une insuffisance rénale aiguë.",
        priorite: "Hyperkaliémie avec anomalies ECG, œdème pulmonaire ou signes urémiques sévères nécessitent une prise en charge urgente et parfois dialyse.",
      },
      {
        nom: "Maladie rénale chronique",
        definition: "Anomalie rénale persistante avec baisse de fonction et/ou marqueurs de lésion sur plusieurs mois, pouvant progresser vers insuffisance rénale terminale.",
        physiopathologie: "La perte progressive de néphrons augmente la charge des néphrons restants, favorise hyperfiltration, fibrose et aggravation progressive.",
        risques: "Diabète, hypertension, maladies glomérulaires, polykystose, âge et épisodes répétés d’atteinte rénale.",
        manifestations: "Souvent asymptomatique tôt; fatigue, prurit, œdèmes, hypertension, anorexie et symptômes urémiques aux stades avancés.",
        examens: "DFG estimé, albuminurie, créatinine, électrolytes, hémoglobine, métabolisme osseux/minéral et échographie selon contexte.",
        traitement: "Contrôle pression et diabète, réduction de l’albuminurie et du risque cardiovasculaire, correction anémie/minéraux et préparation à dialyse ou transplantation si progression.",
        soins: "Surveiller poids, pression, œdèmes, nutrition, anémie, symptômes urémiques et adhésion; vérifier doses médicamenteuses adaptées au DFG.",
        complications: "Anémie, hyperkaliémie, acidose, maladie osseuse-minérale, surcharge, maladie cardiovasculaire et urémie.",
        education: commun.education + " Protéger la fonction rénale, éviter AINS sans avis et comprendre le plan de suivi.",
        points: "La maladie rénale chronique augmente fortement le risque cardiovasculaire.",
        priorite: "Surveiller en priorité surcharge, potassium et symptômes urémiques; toute dyspnée aiguë, faiblesse avec arythmie ou confusion progressive nécessite une évaluation urgente.",
      },
      {
        nom: "Pyélonéphrite",
        definition: "Infection du rein et du bassinet, généralement ascendante à partir des voies urinaires basses.",
        physiopathologie: "Les bactéries remontent vers le rein et provoquent inflammation interstitielle; une obstruction peut favoriser sepsis et abcès.",
        risques: "Grossesse, calculs, reflux, obstruction, diabète, cathéter et anomalies urinaires.",
        manifestations: "Fièvre, frissons, douleur lombaire, nausées, symptômes urinaires et douleur à la percussion costo-vertébrale.",
        examens: "Analyse urinaire et culture; bilan sanguin et imagerie si forme sévère, récidivante ou obstruction suspectée.",
        traitement: "Antibiotiques adaptés à la gravité et aux cultures, hydratation; drainage urgent si obstacle infecté.",
        soins: "Surveiller température, douleur, hydratation, diurèse, signes de sepsis et réponse aux antibiotiques; obtenir culture avant antibiothérapie si possible sans retard dangereux.",
        complications: "Sepsis, abcès rénal, lésion rénale et récidive.",
        education: commun.education + " Hydratation adaptée, observance antibiotique et consultation si aggravation.",
        points: "Fièvre plus douleur lombaire chez un patient à risque doit faire rechercher une infection rénale plutôt qu’une simple cystite.",
        priorite: "Hypotension, confusion, tachypnée ou oligurie avec infection urinaire suggèrent sepsis et nécessitent prise en charge immédiate.",
      },
      {
        nom: "Lithiase urinaire",
        definition: "Formation de calculs dans les voies urinaires pouvant provoquer colique néphrétique, hématurie et obstruction.",
        physiopathologie: "La sursaturation urinaire en sels favorise cristallisation; l’obstruction urétérale entraîne distension et douleur intense.",
        risques: "Faible apport hydrique, troubles métaboliques, infections spécifiques, alimentation et antécédents familiaux.",
        manifestations: "Douleur lombaire intense irradiant vers l’aine, agitation, nausées, vomissements et hématurie.",
        examens: "Analyse urinaire, fonction rénale et imagerie, souvent scanner sans contraste; échographie privilégiée dans certains contextes.",
        traitement: "Analgésie, hydratation adaptée, traitement expulsif sélectionné; intervention si obstruction compliquée ou calcul non expulsable.",
        soins: "Évaluer douleur, urine, fièvre, diurèse; filtrer les urines si demandé pour analyse du calcul et surveiller effets antalgiques.",
        complications: "Infection sur obstacle, hydronéphrose et insuffisance rénale.",
        education: commun.education + " Hydratation et prévention alimentaire dépendent de la composition du calcul.",
        points: "Calcul + infection + obstruction constitue une urgence urologique.",
        priorite: "Fièvre ou sepsis avec obstruction suspectée nécessite alerte urgente pour drainage; ne pas se limiter à traiter la douleur.",
      },
      {
        nom: "Hémodialyse: complications principales",
        definition: "Technique d’épuration extracorporelle retirant déchets et excès d’eau chez des patients avec insuffisance rénale avancée ou indications aiguës.",
        physiopathologie: "Diffusion et ultrafiltration à travers une membrane permettent correction de certaines toxines, électrolytes et surcharge volémique.",
        risques: "Hypotension intradialytique, saignement, infection et dysfonction de l’accès vasculaire.",
        manifestations: "Crampes, hypotension, nausées, céphalées; infection de fistule/cathéter, absence de thrill ou saignement anormal sont préoccupants.",
        examens: "Poids pré/post dialyse, pression, électrolytes et surveillance de l’accès; bilan infectieux si fièvre.",
        traitement: "Adapter ultrafiltration et traitements selon complication; antibiothérapie pour infection et intervention sur accès thrombose/dysfonction.",
        soins: "Ne pas prendre pression ni effectuer ponction sur bras de fistule; vérifier thrill/bruit, protéger accès, surveiller saignement et hypotension.",
        complications: "Hypotension, arythmie, hémorragie, infection, thrombose d’accès et syndrome de déséquilibre.",
        education: commun.education + " Protéger l’accès, reconnaître infection et respecter restrictions individualisées.",
        points: "La fistule artério-veineuse est une ligne de vie à protéger.",
        priorite: "Absence soudaine de thrill, saignement incontrôlé ou signes de sepsis liés à l’accès nécessitent une intervention rapide.",
      },
    ],
    references: [
      { label: "KDIGO — Clinical Practice Guidelines", href: "https://kdigo.org/guidelines/" },
      { label: "National Kidney Foundation — Clinical Resources", href: "https://www.kidney.org/professionals" },
    ],
  },
  {
    slug: "endocrinologie",
    titre: "Système endocrinien",
    objectifs: "Comprendre régulation hormonale et glycémique, reconnaître les urgences diabétiques, thyroïdiennes et surrénaliennes et assurer une surveillance infirmière adaptée.",
    rappel: [
      "Les hormones coordonnent métabolisme, croissance, stress, reproduction et équilibre hydro-électrolytique par des boucles de rétrocontrôle.",
      "Le pancréas endocrine régule la glycémie via insuline et glucagon; thyroïde et surrénales influencent fortement métabolisme et réponse au stress.",
      "Les urgences endocriniennes peuvent se présenter par altération de conscience, déshydratation, arythmies, hypotension ou hyperthermie.",
    ],
    pathologies: [
      {
        nom: "Diabète sucré",
        definition: "Maladie métabolique caractérisée par hyperglycémie chronique due à un déficit de sécrétion d’insuline, d’action de l’insuline ou des deux.",
        physiopathologie: "Type 1: destruction auto-immune des cellules bêta avec déficit absolu. Type 2: insulinorésistance progressive associée à dysfonction des cellules bêta.",
        risques: "Type 2: antécédents familiaux, surpoids, sédentarité, âge, diabète gestationnel et certaines populations à risque; type 1 lié surtout à auto-immunité et susceptibilité génétique.",
        manifestations: "Polyurie, polydipsie, perte de poids, fatigue, infections récurrentes ou découverte asymptomatique; hypoglycémie liée au traitement peut provoquer sueurs, tremblements et confusion.",
        examens: "Glycémie à jeun, HbA1c, test oral de tolérance ou glycémie aléatoire avec symptômes selon critères diagnostiques; recherche des complications.",
        traitement: "Insuline indispensable dans type 1; modifications du mode de vie et médicaments glucose-lowering, incluant insuline si nécessaire, dans type 2 selon profil et comorbidités.",
        soins: "Surveiller glycémie, signes d’hypo/hyperglycémie, pieds, peau et injection; coordonner repas et insuline, vérifier technique et sites d’injection.",
        complications: "Hypoglycémie, acidocétose, état hyperosmolaire, rétinopathie, néphropathie, neuropathie et maladie cardiovasculaire.",
        education: commun.education + " Enseigner autosurveillance, soins des pieds, hypoglycémie, jours de maladie et technique d’insuline.",
        points: "L’hypoglycémie chez un patient traité doit être reconnue et corrigée rapidement; la sécurité prime sur le contrôle glycémique strict.",
        priorite: "Devant confusion ou baisse de conscience chez un patient diabétique, vérifier immédiatement la glycémie et traiter une hypoglycémie selon protocole sans retarder ABC.",
      },
      {
        nom: "Acidocétose diabétique",
        definition: "Urgence métabolique associant hyperglycémie, cétose et acidose, surtout dans le diabète de type 1 mais possible dans d’autres contextes.",
        physiopathologie: "Le manque d’insuline et l’excès d’hormones de stress entraînent lipolyse, production de cétones, acidose osmotique et déshydratation avec déficit corporel en potassium.",
        risques: "Infection, omission d’insuline, nouveau diabète, infarctus, stress physiologique et certains médicaments.",
        manifestations: "Polyurie, polydipsie, déshydratation, nausées, douleur abdominale, respiration de Kussmaul, haleine fruitée et altération de conscience.",
        examens: "Glycémie, cétones, gaz veineux/artériel, bicarbonate, anion gap, potassium, fonction rénale et recherche du facteur déclenchant.",
        traitement: "Liquides IV, insuline IV, remplacement du potassium selon valeurs et surveillance rapprochée; traiter la cause.",
        soins: "Monitorer ECG, glycémie fréquente, potassium, état neurologique, entrées/sorties et réponse aux liquides; ne pas commencer l’insuline si hypokaliémie sévère non corrigée selon protocole.",
        complications: "Hypokaliémie, arythmies, hypoglycémie, œdème cérébral surtout chez l’enfant et choc.",
        education: commun.education + " Ne jamais arrêter l’insuline basale dans le type 1 sans avis; appliquer règles des jours de maladie.",
        points: "Le potassium sérique peut être normal ou élevé malgré un déficit corporel total important.",
        priorite: "Prioriser réanimation liquidienne, potassium et monitorage avant/pendant insulinothérapie; toute altération de conscience ou arythmie exige une réponse immédiate.",
      },
      {
        nom: "État hyperglycémique hyperosmolaire",
        definition: "Urgence caractérisée par hyperglycémie très importante, hyperosmolarité et déshydratation profonde avec peu ou pas de cétose significative.",
        physiopathologie: "Une insulinémie suffisante limite la cétose mais pas l’hyperglycémie; la diurèse osmotique massive entraîne pertes d’eau et électrolytes et hyperosmolarité neurologique.",
        risques: "Diabète type 2, âge avancé, infection, accès limité à l’eau, médicaments et maladie aiguë.",
        manifestations: "Déshydratation majeure, faiblesse, confusion, convulsions ou coma, avec signes classiques d’hyperglycémie.",
        examens: "Glycémie, osmolarité, électrolytes, fonction rénale, cétones et bilan de cause.",
        traitement: "Liquides IV progressifs, correction électrolytique, insuline et traitement du déclencheur.",
        soins: "Surveiller neurologie, glycémie, sodium corrigé, potassium, diurèse et signes de surcharge pendant réhydratation.",
        complications: "Choc, thrombose, troubles électrolytiques, convulsions et décès.",
        education: commun.education + " Hydratation, surveillance glycémique et plan de maladie aiguë.",
        points: "Le déficit hydrique est souvent plus profond que dans l’acidocétose.",
        priorite: "La réhydratation et la surveillance neurologique/électrolytique sont prioritaires; corriger trop brutalement l’osmolarité peut être dangereux.",
      },
      {
        nom: "Hyperthyroïdie et tempête thyroïdienne",
        definition: "Excès d’hormones thyroïdiennes; la tempête thyroïdienne est une décompensation extrême avec hypermétabolisme et défaillance d’organes.",
        physiopathologie: "L’excès de T3/T4 augmente métabolisme et sensibilité adrénergique, accélérant cœur, thermogenèse et consommation d’oxygène.",
        risques: "Maladie de Basedow, nodules toxiques, interruption de traitement, infection, chirurgie ou autre stress chez patient hyperthyroïdien.",
        manifestations: "Perte de poids, chaleur, tremblement, tachycardie, anxiété; tempête: fièvre élevée, tachyarythmie, agitation/délire, vomissements et insuffisance cardiaque.",
        examens: "TSH basse avec hormones thyroïdiennes élevées, ECG et bilan de déclencheur; diagnostic de tempête surtout clinique.",
        traitement: "Antithyroïdiens, bêtabloquage si approprié et traitement définitif selon cause; tempête nécessite traitement intensif multidisciplinaire.",
        soins: "Surveiller température, rythme, pression, conscience et insuffisance cardiaque; réduire stimulation et appliquer mesures de refroidissement prescrites.",
        complications: "Fibrillation auriculaire, insuffisance cardiaque, ostéoporose et tempête thyroïdienne.",
        education: commun.education + " Ne pas interrompre brutalement les antithyroïdiens sans avis et signaler fièvre/mal de gorge sous certains traitements.",
        points: "Tempête thyroïdienne est une urgence clinique; les chiffres hormonaux ne reflètent pas à eux seuls sa gravité.",
        priorite: "Hyperthermie, tachyarythmie et altération mentale chez patient hyperthyroïdien nécessitent ABC, refroidissement, monitorage et traitement urgent.",
      },
      {
        nom: "Insuffisance surrénalienne et crise addisonienne",
        definition: "Déficit en cortisol, parfois associé à déficit en aldostérone; la crise aiguë provoque hypotension et troubles métaboliques potentiellement mortels.",
        physiopathologie: "Le manque de cortisol réduit réponse vasculaire au stress et maintien de la glycémie; déficit en aldostérone favorise pertes de sodium, déshydratation et hyperkaliémie.",
        risques: "Maladie d’Addison, atteinte hypophysaire, arrêt brutal de corticostéroïdes chroniques, infection ou stress majeur.",
        manifestations: "Fatigue, perte de poids, hypotension; crise: choc, vomissements, douleur abdominale, hyponatrémie, hyperkaliémie et hypoglycémie.",
        examens: "Cortisol/ACTH selon contexte, électrolytes et glycémie; en urgence le traitement ne doit pas attendre les résultats si suspicion forte.",
        traitement: "Hydrocortisone IV et liquides isotoniques, correction hypoglycémie/électrolytes et traitement du déclencheur.",
        soins: "Surveiller pression, rythme, glycémie, sodium, potassium, diurèse et réponse aux corticostéroïdes.",
        complications: "Choc réfractaire, arythmies, hypoglycémie sévère et décès.",
        education: commun.education + " Carte/bracelet d’alerte, règles de dose de stress et ne jamais arrêter brutalement corticostéroïdes chroniques.",
        points: "Une hypotension inexpliquée chez patient sous corticothérapie chronique doit faire envisager une insuffisance surrénalienne.",
        priorite: "En crise suspectée, ne pas retarder hydrocortisone et réanimation liquidienne pour attendre les tests; surveiller étroitement potassium et glycémie.",
      },
    ],
    references: [
      { label: "American Diabetes Association — Standards of Care in Diabetes", href: "https://diabetesjournals.org/care/issue" },
      { label: "American Thyroid Association — Professional Guidelines", href: "https://www.thyroid.org/professionals/ata-professional-guidelines/" },
      { label: "Endocrine Society — Clinical Practice Guidelines", href: "https://www.endocrine.org/clinical-practice-guidelines" },
    ],
  },
  {
    slug: "hematologie",
    titre: "Système hématologique",
    objectifs: "Comprendre les fonctions du sang et de l’hémostase, reconnaître anémie, troubles de coagulation et urgences hématologiques, et sécuriser transfusions et traitements anticoagulants.",
    rappel: [
      "Les globules rouges transportent l’oxygène, les leucocytes participent à la défense immunitaire et les plaquettes à l’hémostase.",
      "La coagulation dépend de l’interaction entre paroi vasculaire, plaquettes et facteurs plasmatiques; un déséquilibre peut provoquer saignement ou thrombose.",
      "Une transfusion nécessite vérification rigoureuse de l’identité et une surveillance immédiate des réactions.",
    ],
    pathologies: [
      {
        nom: "Anémie",
        definition: "Diminution de la concentration d’hémoglobine réduisant la capacité de transport de l’oxygène; les causes sont nombreuses.",
        physiopathologie: "L’anémie résulte d’une production insuffisante, d’une perte sanguine ou d’une destruction accrue des globules rouges.",
        risques: "Carence en fer/B12/folates, saignement, maladie rénale, inflammation chronique, hémolyse et atteinte médullaire.",
        manifestations: "Fatigue, pâleur, dyspnée d’effort, tachycardie, vertiges; formes sévères peuvent provoquer angine ou syncope.",
        examens: "NFS, indices érythrocytaires, réticulocytes, ferritine et bilans ciblés selon cause.",
        traitement: "Traiter la cause, remplacer carences, corriger saignement; transfusion selon symptômes, gravité et contexte plutôt qu’un chiffre isolé.",
        soins: "Évaluer tolérance, dyspnée, douleur thoracique, saignement et fatigue; planifier activité et surveiller réponse au traitement.",
        complications: "Ischémie, insuffisance cardiaque à haut débit dans formes sévères et complications de la cause sous-jacente.",
        education: commun.education + " Expliquer traitement de la cause et aliments/suppléments seulement lorsqu’ils sont indiqués.",
        points: "La gravité clinique dépend de la rapidité d’installation et des comorbidités autant que du niveau d’hémoglobine.",
        priorite: "Dyspnée au repos, douleur thoracique, syncope ou instabilité avec anémie nécessitent une évaluation urgente de la perfusion et du saignement actif.",
      },
      {
        nom: "Drépanocytose et crise vaso-occlusive",
        definition: "Maladie génétique de l’hémoglobine où l’HbS polymérise dans certaines conditions, déformant les globules rouges et favorisant hémolyse et vaso-occlusion.",
        physiopathologie: "La falciformation répétée rend les globules rouges rigides, obstrue microcirculation et provoque ischémie douloureuse et atteinte d’organes.",
        risques: "Déshydratation, infection, hypoxie, froid, stress physiologique et haute altitude peuvent déclencher des crises.",
        manifestations: "Douleur intense osseuse ou thoracique, anémie chronique, ictère; syndrome thoracique aigu: douleur thoracique, fièvre, hypoxémie et infiltrat nouveau.",
        examens: "NFS, réticulocytes, bilirubine, saturation et imagerie thoracique si symptômes respiratoires.",
        traitement: "Analgésie rapide, hydratation prudente, oxygène si hypoxémie, traitement infection; hydroxyurée et autres thérapies de fond selon indication.",
        soins: "Évaluer douleur sans jugement, administrer analgésie prescrite rapidement, surveiller respiration, hydratation et fièvre; encourager spirométrie incitative si hospitalisé selon protocole.",
        complications: "Syndrome thoracique aigu, AVC, séquestration splénique, crise aplasique, infection et atteinte multiviscérale.",
        education: commun.education + " Prévenir déshydratation, infections et reconnaître syndrome thoracique aigu.",
        points: "Une douleur thoracique ou hypoxémie chez un patient drépanocytaire doit faire rechercher un syndrome thoracique aigu.",
        priorite: "Prioriser oxygénation et évaluation urgente si douleur thoracique, fièvre ou désaturation; le syndrome thoracique aigu peut évoluer rapidement.",
      },
      {
        nom: "Thrombocytopénie",
        definition: "Diminution du nombre de plaquettes, liée à production réduite, destruction accrue, consommation ou séquestration.",
        physiopathologie: "Le déficit plaquettaire altère l’hémostase primaire et augmente le risque de saignement, surtout à des taux très bas ou avec dysfonction associée.",
        risques: "Médicaments, infections, maladie auto-immune, chimiothérapie, hépatopathie, CIVD et HIT.",
        manifestations: "Pétéchies, purpura, ecchymoses, épistaxis, gingivorragie et saignement prolongé; hémorragie intracrânienne est rare mais grave.",
        examens: "NFS répétée, frottis, coagulation et bilan étiologique; rechercher pseudothrombopénie.",
        traitement: "Dépend de la cause; arrêt médicament causal, immunothérapie, transfusion plaquettaire dans certaines hémorragies ou situations à haut risque.",
        soins: "Précautions saignement, éviter injections IM et traumatismes inutiles, surveiller selles/urines, neurologie et sites de ponction.",
        complications: "Hémorragie digestive, intracrânienne ou postopératoire.",
        education: commun.education + " Éviter AINS/aspirine non prescrits et activités à risque de traumatisme.",
        points: "Le risque hémorragique dépend du contexte clinique et pas seulement du chiffre plaquettaire.",
        priorite: "Céphalée brutale, déficit neurologique ou saignement incontrôlé chez patient thrombocytopénique nécessite une évaluation urgente.",
      },
      {
        nom: "Coagulation intravasculaire disséminée",
        definition: "Activation systémique pathologique de la coagulation entraînant microthromboses et consommation de plaquettes/facteurs, avec risque simultané de thrombose et hémorragie.",
        physiopathologie: "Un déclencheur majeur active massivement thrombine et fibrine; la consommation des facteurs et la fibrinolyse secondaire provoquent saignements diffus.",
        risques: "Sepsis sévère, traumatisme majeur, complications obstétricales, cancer et choc.",
        manifestations: "Saignements aux points de ponction, ecchymoses, hémorragies, ischémie d’organes, hypotension et défaillance multiviscérale.",
        examens: "Plaquettes basses, PT/aPTT souvent prolongés, fibrinogène bas et D-dimères élevés, interprétés avec contexte.",
        traitement: "Traiter la cause; produits sanguins selon hémorragie et déficits; anticoagulation dans certaines situations sélectionnées.",
        soins: "Réduire ponctions inutiles, appliquer pression prolongée, surveiller saignement, perfusion, diurèse, neurologie et tendances biologiques.",
        complications: "Hémorragie massive, thrombose microvasculaire, insuffisance rénale, respiratoire et choc.",
        education: commun.education,
        points: "La CIVD est un syndrome secondaire à une cause grave; corriger uniquement les laboratoires sans traiter le déclencheur est insuffisant.",
        priorite: "Prioriser ABC, contrôle des saignements, perfusion et traitement urgent de la cause sous-jacente, souvent sepsis ou choc.",
      },
      {
        nom: "Réaction transfusionnelle aiguë",
        definition: "Événement indésirable apparaissant pendant ou peu après transfusion, allant d’une réaction fébrile bénigne à une hémolyse aiguë, anaphylaxie ou surcharge circulatoire.",
        physiopathologie: "Les mécanismes varient: incompatibilité immunologique, allergie, contamination, surcharge ou lésion pulmonaire liée à transfusion.",
        risques: "Erreur d’identification, transfusions antérieures, grossesse, insuffisance cardiaque/rénale et antécédent de réaction.",
        manifestations: "Fièvre, frissons, douleur lombaire, dyspnée, urticaire, hypotension, douleur thoracique, anxiété ou hémoglobinurie selon type.",
        examens: "Évaluation clinique immédiate, vérification identité/produit, bilan d’hémolyse et cultures selon suspicion; gaz du sang/imagerie si détresse respiratoire.",
        traitement: "Arrêt immédiat de la transfusion, maintien d’une voie IV avec solution compatible selon protocole, notification de la banque de sang et traitement spécifique.",
        soins: "Rester avec le patient, ABC et signes vitaux, arrêter le produit, vérifier identité et tubulure, prévenir médecin et banque de sang, conserver sac/tubulure pour investigation selon procédure.",
        complications: "Choc, insuffisance rénale, CIVD, œdème pulmonaire et décès.",
        education: commun.education + " Demander au patient de signaler immédiatement frissons, douleur, dyspnée ou démangeaisons pendant transfusion.",
        points: "Toute nouvelle réaction pendant transfusion doit être considérée sérieusement jusqu’à évaluation.",
        priorite: "ARRÊTER immédiatement la transfusion au premier signe suspect, maintenir l’accès veineux selon protocole et évaluer ABC avant toute autre action.",
      },
    ],
    references: [
      { label: "ASH — Clinical Practice Guidelines", href: "https://www.hematology.org/education/clinicians/guidelines-and-quality-care" },
      { label: "AABB — Clinical Resources", href: "https://www.aabb.org/" },
    ],
  },
];

export function getAutreSysteme(slug: string) {
  return autresSystemes.find((systeme) => systeme.slug === slug);
}
