import type { SystemeCours } from "@/lib/cours/autres-systemes";

const education = "Expliquer la cause du déséquilibre, les apports ou restrictions prescrits, les médicaments concernés, l'autosurveillance utile et les signes d'alarme. Insister sur l'absence d'autosupplémentation en électrolytes sans avis professionnel.";

export const equilibreHydroelectrolytique: SystemeCours = {
  slug: "equilibre-hydroelectrolytique",
  titre: "Équilibre hydro-électrolytique et acido-basique",
  objectifs: "Reconnaître les déséquilibres hydriques, sodiques, potassiques, calciques, magnésiques et acido-basiques; relier manifestations et données biologiques; identifier les urgences et appliquer une surveillance infirmière sûre.",
  rappel: [
    "L'eau corporelle se répartit entre compartiments intra- et extracellulaires. Le sodium influence surtout l'osmolarité extracellulaire et l'équilibre hydrique; le potassium est essentiel à l'activité neuromusculaire et cardiaque.",
    "Les reins, les poumons et les systèmes hormonaux participent au maintien du volume, des électrolytes et du pH. Une altération rénale, respiratoire, digestive ou endocrine peut rapidement perturber cet équilibre.",
    "L'interprétation infirmière associe toujours le résultat biologique au contexte clinique, aux tendances, aux médicaments, aux entrées-sorties, au poids, à la fonction rénale, au rythme cardiaque et à l'état neurologique.",
  ],
  pathologies: [
    {
      nom: "Déficit de volume liquidien et déshydratation",
      definition: "Diminution du volume hydrique corporel, avec ou sans pertes proportionnelles d'électrolytes, pouvant réduire le volume circulant efficace.",
      physiopathologie: "Les pertes digestives, rénales, cutanées ou hémorragiques et les apports insuffisants diminuent le volume extracellulaire; la baisse de perfusion peut progresser vers une atteinte rénale et un choc.",
      risques: "Vomissements, diarrhée, fièvre, brûlures, diurétiques, polyurie, jeûne, incapacité à boire, hémorragie et personnes très jeunes ou âgées.",
      manifestations: "Soif, muqueuses sèches, faiblesse, tachycardie, hypotension orthostatique, oligurie, confusion, perte de poids et mauvaise perfusion dans les formes sévères.",
      examens: "Signes vitaux et orthostatisme si approprié, poids, entrées-sorties, diurèse, électrolytes, urée/créatinine, hématocrite et recherche de la cause.",
      traitement: "Correction de la cause et réhydratation orale ou IV adaptée à la gravité, au sodium, aux pertes et aux comorbidités.",
      soins: "Surveiller état mental, perfusion, pression, pouls, poids, muqueuses, entrées-sorties et réponse au remplissage; appliquer prévention des chutes si hypotension.",
      complications: "Choc hypovolémique, lésion rénale aiguë, troubles électrolytiques, syncope et défaillance d'organes.",
      education,
      points: "Les tendances du poids, de la diurèse et des signes vitaux sont souvent plus informatives qu'une mesure isolée.",
      priorite: "Si hypotension, altération de conscience, oligurie marquée ou mauvaise perfusion apparaissent, prioriser ABC, alerte urgente, accès IV et réanimation prescrite.",
    },
    {
      nom: "Excès de volume liquidien",
      definition: "Accumulation excessive de sodium et d'eau dans le compartiment extracellulaire, souvent liée à une incapacité cardiaque ou rénale à gérer la charge hydrique.",
      physiopathologie: "La rétention hydrosodée augmente les pressions vasculaires et favorise œdèmes périphériques et congestion pulmonaire.",
      risques: "Insuffisance cardiaque, maladie rénale, cirrhose, apports IV excessifs et certains traitements.",
      manifestations: "Prise de poids rapide, œdèmes, turgescence jugulaire, hypertension possible, crépitants, dyspnée et orthopnée.",
      examens: "Poids quotidien, entrées-sorties, examen pulmonaire, saturation, électrolytes, fonction rénale et bilan de la cause.",
      traitement: "Restriction hydrosodée selon indication, diurétiques et traitement de la cause; assistance respiratoire si congestion sévère.",
      soins: "Comparer poids quotidien dans des conditions similaires, surveiller respiration, œdèmes, diurèse, pression, électrolytes et réponse aux diurétiques.",
      complications: "Œdème pulmonaire, hypoxémie, troubles électrolytiques et aggravation cardiaque ou rénale.",
      education,
      points: "Une variation rapide du poids peut refléter une modification importante du volume hydrique.",
      priorite: "Dyspnée aiguë, crépitants diffus ou désaturation avec surcharge imposent positionnement, ABC, oxygénation selon besoin et alerte rapide pour œdème pulmonaire possible.",
    },
    {
      nom: "Hyponatrémie",
      definition: "Concentration sérique de sodium inférieure à la plage de référence du laboratoire, souvent liée à un excès relatif d'eau par rapport au sodium.",
      physiopathologie: "La baisse d'osmolarité peut déplacer l'eau vers les cellules cérébrales et provoquer un œdème cérébral, surtout lorsque la chute est rapide ou profonde.",
      risques: "Diurétiques, pertes digestives remplacées par eau seule, SIADH, insuffisance cardiaque, cirrhose, maladie rénale et polydipsie.",
      manifestations: "Nausées, céphalées, confusion, léthargie, faiblesse; convulsions et coma dans les formes sévères.",
      examens: "Sodium sérique répété, osmolarité sérique et urinaire, sodium urinaire, glycémie, fonction rénale et bilan étiologique selon contexte.",
      traitement: "Traiter la cause; restriction hydrique, solution saline ou saline hypertonique dans certaines formes symptomatiques sévères avec correction étroitement contrôlée.",
      soins: "Surveiller neurologie, convulsions, entrées-sorties, sodium sérié et vitesse de correction; appliquer précautions de sécurité.",
      complications: "Œdème cérébral, convulsions, coma; une correction trop rapide d'une hyponatrémie chronique peut causer une lésion neurologique grave.",
      education,
      points: "La gravité dépend du niveau de sodium, mais aussi de la rapidité d'installation et des symptômes neurologiques.",
      priorite: "Confusion aiguë, convulsion ou baisse de conscience avec hyponatrémie nécessite ABC, protection contre les blessures, alerte urgente et correction contrôlée prescrite.",
    },
    {
      nom: "Hypernatrémie",
      definition: "Concentration sérique de sodium supérieure à la plage de référence, traduisant le plus souvent un déficit d'eau par rapport au sodium.",
      physiopathologie: "L'hyperosmolarité extracellulaire attire l'eau hors des cellules, notamment cérébrales, entraînant déshydratation cellulaire et manifestations neurologiques.",
      risques: "Accès limité à l'eau, pertes insensibles ou digestives, diabète insipide, diurèse osmotique et administration hypertonique.",
      manifestations: "Soif, muqueuses sèches, irritabilité, faiblesse, confusion, hyperréflexie, convulsions ou coma si sévère.",
      examens: "Sodium et osmolarité sériques, entrées-sorties, diurèse, osmolarité urinaire, glycémie et fonction rénale.",
      traitement: "Remplacement progressif du déficit en eau et traitement de la cause; la vitesse dépend de la durée et de la gravité.",
      soins: "Surveiller neurologie, sodium sérié, bilan hydrique, glycémie, poids et signes de surcharge pendant la correction.",
      complications: "Déshydratation cérébrale, convulsions, coma; correction inadaptée pouvant provoquer œdème cérébral.",
      education,
      points: "Chez une personne incapable d'exprimer la soif ou d'accéder à l'eau, la prévention est particulièrement importante.",
      priorite: "Altération neurologique sévère ou instabilité avec hypernatrémie impose ABC, évaluation urgente et correction hydrique contrôlée, jamais brutale.",
    },
    {
      nom: "Hypokaliémie",
      definition: "Diminution du potassium sérique sous la plage de référence du laboratoire.",
      physiopathologie: "La baisse du potassium perturbe la repolarisation cellulaire et la contraction des muscles squelettiques, lisses et cardiaques.",
      risques: "Vomissements, diarrhée, diurétiques de l'anse/thiazidiques, pertes rénales, alcalose, insulinothérapie et apports insuffisants.",
      manifestations: "Faiblesse, crampes, fatigue, constipation ou iléus, palpitations et arythmies; anomalies ECG possibles.",
      examens: "Potassium sérié, ECG si déficit important ou symptômes, magnésium, fonction rénale et recherche des pertes.",
      traitement: "Remplacement oral ou IV selon gravité et cause; corriger une hypomagnésémie associée si présente.",
      soins: "Vérifier fonction rénale et diurèse avant supplémentation importante, surveiller ECG lorsque indiqué, contrôler le débit IV et répéter les dosages.",
      complications: "Arythmies potentiellement graves, faiblesse respiratoire, iléus et rhabdomyolyse dans les formes sévères.",
      education,
      points: "Le potassium IV est un médicament à haut risque et ne doit jamais être administré en bolus IV direct.",
      priorite: "Arythmie, faiblesse marquée ou hypokaliémie sévère nécessite monitorage, évaluation urgente et remplacement contrôlé; ne jamais administrer du potassium IV push.",
    },
    {
      nom: "Hyperkaliémie",
      definition: "Élévation du potassium sérique au-dessus de la plage de référence, pouvant devenir rapidement une urgence cardiaque.",
      physiopathologie: "L'excès de potassium extracellulaire modifie le potentiel membranaire et la conduction cardiaque, avec risque d'arythmie et d'arrêt cardiaque.",
      risques: "Lésion ou insuffisance rénale, acidose, destruction tissulaire, déficit en insuline, médicaments retenant le potassium et supplémentation excessive.",
      manifestations: "Faiblesse, paresthésies, nausées et anomalies ECG; bradyarythmies, élargissement QRS et arrêt cardiaque dans les formes graves.",
      examens: "Répéter un résultat inattendu si hémolyse/pseudohyperkaliémie possible sans retarder la prise en charge si signes de gravité; ECG, fonction rénale, glycémie et gaz du sang selon contexte.",
      traitement: "Selon gravité: stabilisation myocardique par calcium IV, déplacement intracellulaire du potassium par insulinothérapie avec glucose et autres mesures, puis élimination du potassium, incluant dialyse dans certaines situations.",
      soins: "Mettre sous monitorage si hyperkaliémie significative, vérifier médicaments et perfusions contenant du potassium, surveiller glycémie lors d'insuline et réévaluer potassium/ECG.",
      complications: "Arythmies malignes et arrêt cardiaque.",
      education,
      points: "Une hyperkaliémie avec anomalies ECG est une urgence même si le patient se sent relativement bien.",
      priorite: "Si ECG anormal, faiblesse importante ou potassium très élevé: monitorage cardiaque, alerte urgente et préparation immédiate au traitement protocolisé.",
    },
    {
      nom: "Troubles du calcium et du magnésium",
      definition: "Déséquilibres d'électrolytes essentiels à l'excitabilité neuromusculaire, la contraction cardiaque, la coagulation et de nombreuses fonctions cellulaires.",
      physiopathologie: "Un calcium ionisé bas augmente l'excitabilité neuromusculaire; un calcium élevé peut déprimer les fonctions neurologiques et rénales. Le magnésium influence conduction neuromusculaire et rythme cardiaque et interagit avec potassium et calcium.",
      risques: "Maladie rénale, troubles parathyroïdiens, déficit en vitamine D, pancréatite, pertes digestives, diurétiques, alcool, médicaments et supplémentation excessive.",
      manifestations: "Hypocalcémie/hypomagnésémie: paresthésies, crampes, tétanie, convulsions, QT prolongé ou arythmies. Hypercalcémie/hypermagnésémie: faiblesse, léthargie, hypotension, troubles du rythme et dépression des réflexes selon gravité.",
      examens: "Calcium total et/ou ionisé selon contexte, magnésium, albumine, fonction rénale, ECG et bilan étiologique.",
      traitement: "Correction de la cause et remplacement ou réduction de l'électrolyte selon le trouble; traitements IV dans les formes symptomatiques sévères sous surveillance.",
      soins: "Surveiller état neurologique, réflexes, ECG, respiration et fonction rénale; appliquer précautions convulsions/chutes lorsque nécessaire et contrôler les perfusions concentrées.",
      complications: "Convulsions, laryngospasme, arythmies, hypotension, dépression respiratoire et arrêt cardiaque selon le déséquilibre.",
      education,
      points: "Une hypomagnésémie peut rendre une hypokaliémie difficile à corriger; les électrolytes doivent être interprétés ensemble.",
      priorite: "Tétanie, convulsion, arythmie, hypotension ou dépression respiratoire impose ABC, monitorage et correction urgente prescrite.",
    },
    {
      nom: "Acidose et alcalose respiratoires",
      definition: "Troubles primaires du pH provoqués par une modification de la ventilation alvéolaire et donc de la PaCO2.",
      physiopathologie: "Hypoventilation: rétention de CO2 et acidose respiratoire. Hyperventilation: élimination excessive de CO2 et alcalose respiratoire; les reins compensent progressivement.",
      risques: "Acidose: dépression respiratoire, BPCO décompensée, obstruction, atteinte neuromusculaire. Alcalose: douleur, anxiété, hypoxémie, sepsis et ventilation mécanique excessive.",
      manifestations: "Acidose: céphalée, somnolence, confusion, dyspnée. Alcalose: étourdissement, paresthésies, crampes et symptômes de la cause sous-jacente.",
      examens: "Gaz du sang, fréquence et qualité respiratoires, SpO2, électrolytes et recherche de la cause.",
      traitement: "Corriger la cause et assurer une ventilation/oxygénation adéquate; ajuster assistance ventilatoire si indiquée.",
      soins: "Évaluer voies aériennes et ventilation avant de se focaliser sur le chiffre de pH; surveiller conscience, respiration, gaz du sang et réponse au traitement.",
      complications: "Insuffisance respiratoire, arythmies, altération neurologique et déséquilibres électrolytiques.",
      education,
      points: "Un trouble respiratoire du pH est d'abord un problème de ventilation; rechercher pourquoi le patient hypo- ou hyperventile.",
      priorite: "Bradypnée, épuisement, baisse de conscience ou hypoxémie impose ABC et assistance ventilatoire urgente selon besoin; ne pas traiter une hyperventilation inexpliquée comme simple anxiété avant d'exclure une cause grave.",
    },
    {
      nom: "Acidose et alcalose métaboliques",
      definition: "Troubles primaires du bicarbonate liés à une accumulation/perte d'acides ou de bases, avec compensation respiratoire.",
      physiopathologie: "Acidose métabolique: gain d'acides ou perte de bicarbonate, par exemple acidocétose, lactate, insuffisance rénale ou diarrhée. Alcalose métabolique: perte d'acides ou gain de bicarbonate, souvent vomissements, aspiration gastrique ou diurétiques.",
      risques: "Sepsis/choc, diabète décompensé, insuffisance rénale, diarrhée, intoxications, vomissements, diurétiques et pertes gastriques.",
      manifestations: "Acidose: respiration profonde/rapide, nausées, faiblesse, confusion. Alcalose: faiblesse, crampes, paresthésies, hypoventilation compensatrice et arythmies associées aux troubles électrolytiques.",
      examens: "Gaz du sang, bicarbonate, électrolytes, trou anionique lorsque pertinent, lactate, glycémie/cétones, fonction rénale et bilan de la cause.",
      traitement: "Traiter la cause: perfusion et perfusion tissulaire, insulinothérapie de l'acidocétose, correction des pertes digestives/électrolytiques, dialyse ou autres traitements selon indication.",
      soins: "Surveiller ABC, perfusion, neurologie, glycémie, électrolytes, ECG et gaz du sang; réévaluer fréquemment pendant la correction.",
      complications: "Arythmies, instabilité hémodynamique, altération neurologique et défaillance d'organes selon la cause et la sévérité.",
      education,
      points: "Le pH ne doit jamais être interprété isolément: relier pH, PaCO2, bicarbonate et contexte clinique.",
      priorite: "Acidose avec choc, sepsis, acidocétose sévère ou altération de conscience exige ABC et traitement urgent de la cause; la normalisation du pH seule n'est pas l'objectif principal.",
    },
  ],
  references: [
    { label: "WHO — Control of concentrated electrolyte solutions", href: "https://www.who.int/publications/m/item/patient-safety-solution-control-of-concentrated-electrolyte-solutions" },
    { label: "NCBI Bookshelf — Nursing Fundamentals: Fluids and Electrolytes", href: "https://www.ncbi.nlm.nih.gov/books/NBK591820/" },
  ],
};
