export const oncologie = {
  slug: "oncologie",
  titre: "Oncologie et soins infirmiers en cancérologie",
  objectifs: "Comprendre les principes essentiels de la cancérologie, reconnaître les complications des traitements et les urgences oncologiques, assurer une surveillance infirmière sécuritaire et intégrer l’éducation, le soutien psychosocial et les soins palliatifs dans le continuum de soins.",
  rappel: [
    "Le cancer résulte d’une prolifération cellulaire anormale pouvant envahir les tissus voisins et se disséminer à distance par métastases. Le type histologique, le stade, l’état général et les objectifs de soins orientent la prise en charge.",
    "Le traitement peut associer chirurgie, radiothérapie et traitements systémiques. La surveillance infirmière recherche à la fois l’efficacité, les toxicités, les complications infectieuses ou métaboliques et l’impact fonctionnel et psychosocial.",
  ],
  pathologies: [
    {
      nom: "Principes de prise en charge du patient atteint de cancer",
      definition: "La prise en charge oncologique couvre le diagnostic, la stadification, le traitement, les soins de support, la surveillance après traitement et, lorsque nécessaire, les soins palliatifs.",
      physiopathologie: "Les cellules malignes échappent aux mécanismes normaux de contrôle de la croissance, peuvent infiltrer les tissus et se disséminer par voies lymphatique ou sanguine. Les manifestations dépendent de l’organe atteint et de l’extension de la maladie.",
      risques: "Tabac, alcool, certaines infections oncogènes, expositions environnementales ou professionnelles, rayonnements ultraviolets ou ionisants, prédispositions génétiques et certains facteurs métaboliques ou liés au mode de vie.",
      manifestations: "Variables selon le cancer : masse, douleur persistante, saignement inexpliqué, perte pondérale, fatigue, modification d’une fonction d’organe, adénopathies ou symptômes persistants inexpliqués.",
      examens: "Imagerie, analyses biologiques, endoscopie selon le site et confirmation histologique par cytologie ou biopsie. La stadification évalue l’extension de la maladie.",
      traitement: "Chirurgie, radiothérapie, chimiothérapie, hormonothérapie, thérapies ciblées, immunothérapie ou associations selon le type de cancer, le stade, le profil du patient et les ressources disponibles.",
      soins: "Évaluer douleur, nutrition, hydratation, fatigue, mobilité, peau et muqueuses, risque infectieux, état psychosocial et compréhension du plan de soins. Coordonner les soins multidisciplinaires et repérer rapidement toute détérioration.",
      complications: "Progression ou métastases, obstruction ou compression d’organe, infection, thrombose, hémorragie, dénutrition et complications liées aux traitements.",
      education: "Expliquer le plan thérapeutique, les effets indésirables attendus, les signes d’alarme et l’importance des rendez-vous. Soutenir les décisions éclairées, les préférences et les besoins psychosociaux du patient.",
      points: "Le cancer n’est pas une seule maladie. Le diagnostic précis et le stade conditionnent le traitement ; les soins infirmiers accompagnent tout le continuum de soins.",
      priorite: "Identifier immédiatement toute menace vitale ou complication aiguë, puis assurer une surveillance structurée des symptômes, des toxicités et de l’état fonctionnel.",
    },
    {
      nom: "Chimiothérapie et traitements systémiques : surveillance et sécurité",
      definition: "Les traitements systémiques comprennent notamment chimiothérapie cytotoxique, hormonothérapie, thérapies ciblées et immunothérapie. Leurs toxicités varient selon les agents et protocoles.",
      physiopathologie: "Les médicaments anticancéreux ciblent les cellules tumorales ou leurs mécanismes de croissance, mais peuvent aussi affecter des tissus sains ou déclencher des réactions immunitaires et inflammatoires.",
      risques: "Myélosuppression, nausées-vomissements, mucite, diarrhée ou constipation, fatigue, alopécie, toxicités rénale, hépatique, cardiaque, neurologique ou cutanée selon le traitement.",
      manifestations: "Fièvre, frissons, fatigue inhabituelle, saignements, dyspnée, douleur, lésions buccales, troubles digestifs, éruption, neuropathie ou altération de l’état général doivent être évalués dans leur contexte thérapeutique.",
      examens: "NFS et formule leucocytaire, plaquettes, fonctions rénale et hépatique, électrolytes et examens spécifiques au médicament ou au protocole. Vérifier les paramètres requis avant administration.",
      traitement: "Administration selon protocole oncologique validé, avec prémédications et soins de support prescrits. Les toxicités sévères peuvent imposer interruption, adaptation ou traitement spécifique par l’équipe oncologique.",
      soins: "Vérifier identité, médicament, dose, voie, protocole, accès vasculaire et paramètres biologiques requis. Surveiller pendant et après l’administration. Devant douleur, brûlure, gonflement ou résistance au site IV, arrêter l’administration et suivre immédiatement le protocole d’extravasation sans improviser.",
      complications: "Neutropénie, thrombopénie, anémie, infection, hémorragie, extravasation, réactions d’hypersensibilité et toxicités d’organes.",
      education: "Apprendre au patient à signaler rapidement fièvre, saignement, dyspnée, diarrhée importante, vomissements persistants, diminution des urines, douleur inhabituelle ou symptômes neurologiques.",
      points: "La sécurité repose sur le respect strict du protocole, la vérification des paramètres prétraitement et la détection précoce des toxicités.",
      priorite: "Avant toute administration, confirmer que les conditions de sécurité du protocole sont remplies ; pendant le traitement, interrompre et escalader immédiatement toute réaction aiguë ou suspicion d’extravasation.",
    },
    {
      nom: "Radiothérapie : soins cutanés et surveillance",
      definition: "La radiothérapie utilise des rayonnements ionisants pour détruire ou contrôler les cellules cancéreuses dans une zone ciblée.",
      physiopathologie: "Les rayonnements endommagent l’ADN cellulaire. Les tissus sains situés dans le champ irradié peuvent également présenter des effets indésirables aigus ou tardifs.",
      risques: "Réactions cutanées, fatigue et toxicités propres à la zone irradiée : mucite, dysphagie, troubles digestifs, urinaires ou hématologiques selon le site et le volume traités.",
      manifestations: "Érythème, sécheresse ou desquamation cutanée, fatigue et symptômes localisés au champ traité. Rechercher douleur importante, infection, déshydratation ou incapacité à s’alimenter.",
      examens: "Évaluation clinique régulière de la peau, de la nutrition, de l’hydratation et des toxicités spécifiques ; examens biologiques ou d’imagerie selon le protocole.",
      traitement: "Radiothérapie selon plan spécialisé, associée à des mesures de support et parfois à un traitement systémique concomitant.",
      soins: "Inspecter la zone irradiée, évaluer douleur, fatigue, alimentation et hydratation. Appliquer uniquement les produits et mesures cutanées recommandés par le service de radiothérapie et préserver les repères de traitement.",
      complications: "Dermite sévère, dénutrition, déshydratation, infection secondaire et toxicités tardives spécifiques aux organes exposés.",
      education: "Éviter friction et irritation de la zone ; suivre les consignes du service concernant toilette, produits cutanés, soleil et vêtements. Signaler toute aggravation importante.",
      points: "Les effets indésirables sont souvent localisés au champ irradié ; les conseils cutanés doivent rester compatibles avec le protocole du centre.",
      priorite: "Détecter une toxicité qui compromet peau, alimentation, hydratation ou fonction d’organe et la signaler rapidement à l’équipe de radiothérapie.",
    },
    {
      nom: "Neutropénie fébrile et risque infectieux",
      definition: "La neutropénie fébrile associe fièvre et diminution importante des neutrophiles chez un patient immunodéprimé par le cancer ou son traitement ; elle constitue une urgence potentiellement vitale.",
      physiopathologie: "La réduction des neutrophiles diminue la capacité à contenir une infection. Les signes inflammatoires peuvent être discrets et l’infection évoluer rapidement vers sepsis et choc.",
      risques: "Chimiothérapie myélosuppressive, hémopathies malignes, greffe, neutropénie profonde ou prolongée, dispositifs invasifs et altération des barrières cutanéo-muqueuses.",
      manifestations: "Fièvre ou frissons, malaise, hypotension, tachycardie, dyspnée, confusion ; un foyer local peut être peu symptomatique.",
      examens: "NFS avec neutrophiles, cultures et prélèvements selon le tableau, bilan de fonction d’organe et examens ciblés sans retarder la prise en charge urgente.",
      traitement: "Évaluation médicale urgente et antibiothérapie empirique rapide selon protocole local, adaptée ensuite aux données microbiologiques et cliniques.",
      soins: "Reconnaître immédiatement la fièvre chez un patient neutropénique, évaluer les constantes et signes de sepsis, appliquer les précautions d’hygiène et préparer rapidement prélèvements et traitement prescrits.",
      complications: "Sepsis, choc septique, défaillance multiviscérale et décès.",
      education: "Mesurer et signaler immédiatement une fièvre selon le seuil communiqué par l’équipe oncologique ; éviter l’automédication qui pourrait masquer la fièvre et respecter les mesures de prévention des infections.",
      points: "Chez un patient neutropénique, la fièvre peut être le seul signe d’une infection grave. L’évaluation ne doit pas être différée.",
      priorite: "Traiter toute fièvre chez un patient neutropénique comme une urgence : évaluer, alerter et faciliter sans délai la prise en charge antimicrobienne prescrite.",
    },
    {
      nom: "Syndrome de lyse tumorale",
      definition: "Le syndrome de lyse tumorale est une urgence métabolique due à la destruction rapide de cellules tumorales avec libération massive de potassium, phosphate et acides nucléiques.",
      physiopathologie: "La lyse cellulaire entraîne hyperkaliémie, hyperphosphatémie, hyperuricémie et hypocalcémie secondaire, pouvant provoquer arythmies, convulsions et insuffisance rénale aiguë.",
      risques: "Hémopathies ou tumeurs très prolifératives, masse tumorale importante, forte sensibilité au traitement, fonction rénale altérée et début d’un traitement anticancéreux efficace.",
      manifestations: "Nausées, vomissements, faiblesse, crampes, paresthésies, diminution des urines, confusion, convulsions ou arythmies ; les anomalies biologiques peuvent précéder les symptômes.",
      examens: "Surveillance rapprochée du potassium, phosphate, calcium, acide urique, créatinine, diurèse et ECG selon le niveau de risque et le protocole.",
      traitement: "Prévention et traitement selon protocole : hydratation adaptée, agents hypouricémiants prescrits, correction prudente des anomalies électrolytiques et prise en charge rénale urgente si nécessaire.",
      soins: "Surveiller bilan hydrique, diurèse, neurologie, ECG et résultats biologiques. Éviter toute supplémentation électrolytique non indiquée et signaler immédiatement les anomalies menaçantes.",
      complications: "Arythmie maligne, convulsions, insuffisance rénale aiguë, arrêt cardiaque et décès.",
      education: "Expliquer l’importance des bilans répétés et demander de signaler faiblesse, palpitations, crampes, baisse des urines ou symptômes neurologiques.",
      points: "Le syndrome de lyse tumorale peut être anticipé chez les patients à risque ; la prévention et la surveillance biologique sont essentielles.",
      priorite: "Repérer immédiatement hyperkaliémie, arythmie, baisse de diurèse ou signes neurologiques et déclencher la prise en charge urgente selon protocole.",
    },
    {
      nom: "Urgences oncologiques par compression ou obstruction",
      definition: "Certaines tumeurs ou métastases peuvent comprimer rapidement une structure vitale, notamment moelle épinière, voies aériennes, gros vaisseaux ou organes creux.",
      physiopathologie: "La croissance tumorale, l’œdème ou l’infiltration peuvent compromettre perfusion, drainage veineux, fonction neurologique ou perméabilité d’un organe.",
      risques: "Cancer connu avec progression ou métastases, tumeurs thoraciques, vertébrales, abdominales ou cérébrales selon la complication.",
      manifestations: "Nouvelle faiblesse ou déficit neurologique, douleur rachidienne intense, troubles sphinctériens, dyspnée, œdème cervico-facial, dysphagie, distension ou symptômes d’obstruction selon le site.",
      examens: "Évaluation ABCDE et neurologique, imagerie urgente adaptée au syndrome suspecté et bilans ciblés selon la stabilité clinique.",
      traitement: "Traitement urgent dirigé contre la cause et la compression : mesures de stabilisation, médicaments, radiothérapie, procédure interventionnelle ou chirurgie selon l’indication spécialisée.",
      soins: "Identifier les symptômes nouveaux, documenter l’évolution, protéger les fonctions vitales et neurologiques, éviter les retards diagnostiques et préparer les interventions urgentes prescrites.",
      complications: "Paralysie permanente, insuffisance respiratoire, thrombose, ischémie, perforation ou défaillance d’organe selon la structure atteinte.",
      education: "Demander au patient de signaler sans attendre faiblesse nouvelle, perte de sensibilité, troubles urinaires ou fécaux, dyspnée aiguë, gonflement du visage ou douleur rachidienne inhabituelle.",
      points: "Une modification neurologique ou respiratoire récente chez un patient cancéreux peut traduire une urgence compressive et nécessite une évaluation rapide.",
      priorite: "Devant déficit neurologique aigu, détresse respiratoire ou syndrome compressif suspecté, prioriser ABCDE, alerter immédiatement et accélérer l’imagerie et le traitement spécialisé.",
    },
    {
      nom: "Douleur, symptômes, soins palliatifs et soutien psychosocial",
      definition: "Les soins palliatifs visent à prévenir et soulager la souffrance physique, psychosociale et spirituelle et peuvent être intégrés précocement aux traitements anticancéreux.",
      physiopathologie: "La douleur et les autres symptômes peuvent résulter de la tumeur, des métastases, des traitements ou de comorbidités. La souffrance globale inclut aussi anxiété, détresse sociale, perte d’autonomie et préoccupations spirituelles.",
      risques: "Cancer avancé, forte charge symptomatique, douleur persistante, dyspnée, dénutrition, fatigue, isolement, difficultés financières ou familiales et progression de la maladie.",
      manifestations: "Douleur, dyspnée, nausées, constipation, fatigue, anorexie, insomnie, anxiété, tristesse, peur ou détresse existentielle.",
      examens: "Évaluation régulière et multidimensionnelle des symptômes, de la douleur, du fonctionnement, des objectifs et préférences de soins ; examens complémentaires uniquement lorsqu’ils contribuent aux objectifs de prise en charge.",
      traitement: "Traitement pharmacologique et non pharmacologique des symptômes, soutien psychosocial et spirituel, réadaptation et soins palliatifs adaptés aux besoins et préférences.",
      soins: "Évaluer systématiquement douleur et symptômes, administrer les traitements prescrits, prévenir les effets indésirables, soutenir le patient et les proches, faciliter la communication sur les objectifs de soins et coordonner les ressources disponibles.",
      complications: "Souffrance non contrôlée, déclin fonctionnel, dénutrition, déshydratation, détresse psychologique et hospitalisations évitables.",
      education: "Expliquer que les soins palliatifs ne signifient pas abandonner les traitements : ils peuvent accompagner les soins visant à prolonger la vie et améliorer la qualité de vie.",
      points: "Le soulagement de la souffrance fait partie des soins oncologiques. Les besoins physiques, psychologiques, sociaux et spirituels doivent être considérés ensemble.",
      priorite: "Soulager rapidement les symptômes sévères, rechercher les causes réversibles compatibles avec les objectifs de soins et respecter les préférences du patient dans une approche centrée sur la personne.",
    },
  ],
  references: [
    { label: "OMS — Cancer : fiche d’information", href: "https://www.who.int/fr/news-room/fact-sheets/detail/cancer" },
    { label: "OMS — Cancer : prévention, diagnostic, traitement et suivi", href: "https://www.who.int/fr/health-topics/cancer" },
    { label: "OMS — Soins palliatifs", href: "https://www.who.int/fr/news-room/fact-sheets/detail/palliative-care" },
  ],
};
