import type { SystemeCours } from "@/lib/cours/autres-systemes";

const education = "Expliquer les objectifs des soins, les exercices respiratoires et de mobilisation, la gestion de la douleur, les soins de plaie, les médicaments prescrits et les signes d'alarme. Vérifier la compréhension avant la sortie et adapter l'enseignement aux ressources du patient.";

export const perioperatoire: SystemeCours = {
  slug: "perioperatoire",
  titre: "Soins périopératoires et complications chirurgicales",
  objectifs: "Préparer le patient à une intervention, assurer une surveillance postopératoire structurée, reconnaître rapidement les complications chirurgicales et mettre en œuvre les priorités infirmières de sécurité, oxygénation, perfusion, prévention des infections et récupération fonctionnelle.",
  rappel: [
    "La période périopératoire comprend les phases préopératoire, peropératoire et postopératoire. La sécurité repose sur l'identification correcte du patient, du site et de la procédure, l'évaluation des allergies et risques, la communication d'équipe et une surveillance structurée.",
    "Au réveil, les priorités suivent ABC : perméabilité des voies aériennes, ventilation et oxygénation, puis circulation et perfusion. L'état neurologique, la douleur, la température, la plaie, les drains et la diurèse complètent l'évaluation.",
    "La mobilisation précoce adaptée, les exercices respiratoires, la prévention thromboembolique, une analgésie sûre et une bonne hygiène réduisent plusieurs complications postopératoires.",
  ],
  pathologies: [
    {
      nom: "Préparation préopératoire et sécurité chirurgicale",
      definition: "Ensemble des vérifications et soins réalisés avant une intervention afin de réduire les erreurs évitables et préparer le patient sur les plans clinique, psychologique et logistique.",
      physiopathologie: "L'anesthésie et la chirurgie modifient respiration, circulation, thermorégulation, coagulation et réponse au stress. Les maladies chroniques, allergies, médicaments et risques d'aspiration ou de saignement peuvent augmenter les complications.",
      risques: "Erreur d'identité ou de site, consentement incomplet, allergie méconnue, anticoagulants, diabète, dénutrition, infection active, voie aérienne difficile, jeûne inadéquat et examens essentiels non disponibles.",
      manifestations: "Cette rubrique est préventive : rechercher anxiété, douleur, anomalies des signes vitaux, infection, déshydratation, hypoglycémie/hyperglycémie et tout changement clinique avant le transfert au bloc.",
      examens: "Vérifier les examens prescrits selon l'intervention et le patient : hémogramme, coagulation, électrolytes, glycémie, groupage, ECG, imagerie ou autres évaluations ciblées.",
      traitement: "Optimisation des maladies associées, médicaments préopératoires prescrits, antibioprophylaxie lorsqu'indiquée et préparation spécifique selon la chirurgie.",
      soins: "Confirmer identité, intervention, site, consentement, allergies, jeûne et médicaments; documenter les constantes; retirer ou gérer les objets selon protocole; sécuriser les effets personnels; assurer transmission et checklist institutionnelle.",
      complications: "Erreur de patient/site/procédure, aspiration, réaction allergique, hémorragie, infection, déséquilibre glycémique et retard ou annulation évitable.",
      education: education + " Expliquer le jeûne prescrit, la respiration profonde, la toux soutenue, la mobilisation et la prise en charge prévue de la douleur.",
      points: "Une checklist ne remplace pas le jugement clinique : toute nouvelle anomalie significative doit être signalée avant l'intervention.",
      priorite: "Ne pas laisser progresser le parcours opératoire si l'identité, le site/procédure, le consentement, une allergie majeure ou un risque critique ne sont pas clarifiés. Alerter l'équipe et résoudre l'écart avant la suite.",
    },
    {
      nom: "Surveillance postopératoire immédiate",
      definition: "Évaluation systématique du patient au réveil afin de détecter précocement une obstruction des voies aériennes, hypoventilation, hypoxémie, instabilité circulatoire, douleur ou complication de l'anesthésie.",
      physiopathologie: "Les anesthésiques, opioïdes, pertes liquidiennes, douleur et effets de la chirurgie peuvent déprimer la ventilation, diminuer les réflexes protecteurs et altérer la perfusion.",
      risques: "Âge avancé, apnée du sommeil, obésité, maladie respiratoire ou cardiaque, opioïdes/sédatifs, chirurgie majeure et pertes sanguines.",
      manifestations: "Somnolence excessive, obstruction, ronflement inhabituel, bradypnée, désaturation, hypotension, tachycardie, agitation, douleur, nausées, hypothermie ou saignement.",
      examens: "Surveillance répétée des signes vitaux, SpO2, état de conscience, douleur, plaie/drains, bilan entrées-sorties et examens ciblés selon l'évolution.",
      traitement: "Oxygène, soutien des voies aériennes/ventilation, remplissage, antiémétiques, analgésie multimodale et traitements spécifiques selon prescription et cause.",
      soins: "Prioriser ABC, positionner de façon sûre, surveiller fréquence et qualité respiratoires, saturation, pression, pouls, conscience, douleur, température, pansement, drains et diurèse; réévaluer après chaque intervention.",
      complications: "Obstruction, dépression respiratoire, aspiration, hypoxémie, choc, arythmie, délirium, hypothermie et douleur non contrôlée.",
      education: education,
      points: "Une saturation acceptable ne suffit pas si le patient hypoventile sous oxygène; la fréquence respiratoire et le niveau de conscience restent essentiels.",
      priorite: "Toute obstruction, bradypnée, désaturation, baisse de conscience ou instabilité hémodynamique impose ABC immédiat, appel d'aide et traitement protocolisé.",
    },
    {
      nom: "Hémorragie postopératoire et choc hypovolémique",
      definition: "Perte sanguine postopératoire pouvant réduire le volume circulant et entraîner une hypoperfusion tissulaire puis une défaillance d'organes.",
      physiopathologie: "La baisse du volume intravasculaire diminue le retour veineux, le débit cardiaque et l'apport d'oxygène. La compensation initiale par tachycardie et vasoconstriction peut précéder l'hypotension.",
      risques: "Chirurgie majeure, trouble de coagulation, anticoagulants, hypertension non contrôlée, saignement peropératoire important et problème d'hémostase.",
      manifestations: "Tachycardie, pâleur, peau froide, agitation, faiblesse, hypotension tardive, oligurie, pansement saturé, drainage sanguin croissant ou distension selon le site.",
      examens: "Signes vitaux sériés, hémogramme, coagulation, lactate et autres examens selon le contexte; quantifier les pertes et surveiller les drains.",
      traitement: "Contrôle de la source, accès vasculaire, liquides et produits sanguins selon indication, correction des troubles de coagulation et reprise chirurgicale si nécessaire.",
      soins: "Reconnaître la tendance des signes vitaux, inspecter plaie et drains, quantifier les pertes, maintenir accès IV, administrer les traitements prescrits, surveiller perfusion et diurèse et préparer une escalade rapide.",
      complications: "Choc, ischémie myocardique, lésion rénale aiguë, coagulopathie, défaillance multiviscérale et décès.",
      education: education + " Après la sortie, signaler immédiatement saignement important, malaise, syncope ou faiblesse brutale.",
      points: "La tachycardie et la modification de l'état mental peuvent précéder l'hypotension dans une hémorragie significative.",
      priorite: "Si hémorragie ou choc suspecté : ABC, oxygénation selon besoin, alerte immédiate, accès IV fonctionnel, quantification des pertes et préparation à la réanimation et au contrôle de la source.",
    },
    {
      nom: "Infection du site opératoire",
      definition: "Infection touchant l'incision ou des tissus/organes liés à l'intervention, apparaissant après une chirurgie.",
      physiopathologie: "Une contamination microbienne associée à une défense locale ou systémique insuffisante peut entraîner inflammation, suppuration et parfois extension profonde ou sepsis.",
      risques: "Diabète mal contrôlé, tabagisme, obésité, dénutrition, contamination opératoire, durée prolongée, mauvaise asepsie et immunodépression.",
      manifestations: "Douleur croissante, rougeur, chaleur, œdème, écoulement purulent, mauvaise cicatrisation, fièvre ou signes systémiques.",
      examens: "Inspection de la plaie, température et bilan clinique; prélèvement/culture lorsqu'indiqué, hémogramme et imagerie si infection profonde suspectée.",
      traitement: "Soins locaux, drainage lorsqu'indiqué et antibiothérapie selon profondeur, sévérité et microbiologie; contrôle glycémique et traitement du sepsis si présent.",
      soins: "Hygiène des mains et technique aseptique, surveillance structurée de la plaie, documentation de l'aspect et des écoulements, contrôle des facteurs de risque et administration correcte des traitements prescrits.",
      complications: "Abcès, déhiscence, infection profonde, sepsis, retard de cicatrisation et réintervention.",
      education: education + " Enseigner hygiène des mains, soins de plaie et signes d'infection nécessitant une consultation.",
      points: "Une fièvre isolée n'établit pas une infection du site; l'évolution de la plaie et l'état général doivent être évalués ensemble.",
      priorite: "Si infection avec hypotension, confusion, tachypnée ou mauvaise perfusion, rechercher un sepsis et déclencher rapidement l'évaluation et le traitement protocolisés.",
    },
    {
      nom: "Déhiscence et éviscération",
      definition: "La déhiscence est l'ouverture partielle ou complète d'une incision; l'éviscération correspond à la protrusion de viscères à travers la plaie ouverte.",
      physiopathologie: "Une cicatrisation insuffisante ou une augmentation brutale de pression sur la paroi peut rompre les plans suturés.",
      risques: "Infection, dénutrition, obésité, diabète, corticothérapie, toux/vomissements importants et chirurgie abdominale.",
      manifestations: "Sensation de déchirure, augmentation d'un drainage sérosanguinolent, ouverture visible de la plaie; en éviscération, organes ou tissus protrudent.",
      examens: "Diagnostic principalement clinique avec évaluation immédiate de la stabilité; examens supplémentaires après sécurisation selon l'équipe chirurgicale.",
      traitement: "Urgence chirurgicale pour éviscération; protection de la plaie et réparation selon la gravité.",
      soins: "Rester avec le patient, réduire les efforts, positionner pour diminuer la tension abdominale, couvrir les viscères avec compresses stériles humidifiées au sérum physiologique selon protocole, garder à jeun et alerter immédiatement. Ne jamais repousser les organes.",
      complications: "Infection, lésion/ischémie viscérale, péritonite, sepsis et nouvelle chirurgie.",
      education: education + " Enseigner soutien de l'incision lors de la toux et éviter les efforts non autorisés.",
      points: "Une éviscération est une urgence; les viscères doivent être protégés sans tentative de réintroduction au lit du patient.",
      priorite: "Alerter immédiatement, protéger les viscères avec une couverture stérile humidifiée selon protocole, garder NPO, surveiller ABC et préparer le retour urgent au bloc.",
    },
    {
      nom: "Thrombose veineuse profonde et embolie pulmonaire postopératoires",
      definition: "Complications thromboemboliques favorisées par stase veineuse, lésion vasculaire et hypercoagulabilité autour de la chirurgie.",
      physiopathologie: "Un thrombus veineux profond peut se former surtout aux membres inférieurs; sa migration vers les artères pulmonaires peut provoquer une embolie pulmonaire et une surcharge aiguë du ventricule droit.",
      risques: "Immobilité, chirurgie majeure ou orthopédique, cancer, antécédent thromboembolique, âge, obésité et autres facteurs individuels.",
      manifestations: "TVP : gonflement, douleur, chaleur ou asymétrie d'un membre. EP : dyspnée brutale, douleur thoracique, tachycardie, hypoxémie, syncope ou hypotension.",
      examens: "Échographie veineuse pour TVP; évaluation de probabilité et imagerie pulmonaire selon le contexte pour EP.",
      traitement: "Prévention mécanique/pharmacologique selon risque; anticoagulation et stratégie de reperfusion dans certaines EP graves.",
      soins: "Favoriser mobilisation précoce prescrite, exercices des jambes, dispositifs de compression et prophylaxie médicamenteuse correctement administrée; surveiller saignement et signes thromboemboliques.",
      complications: "EP, choc obstructif, syndrome post-thrombotique, récidive et décès.",
      education: education + " Expliquer mobilité, prophylaxie prescrite et signes de TVP/EP.",
      points: "Une dyspnée postopératoire brutale inexpliquée doit faire rechercher une EP parmi les diagnostics urgents.",
      priorite: "En cas de dyspnée brutale, syncope, douleur thoracique ou hypoxémie : limiter l'effort, ABC, oxygénation/monitorage selon besoin et alerte urgente.",
    },
    {
      nom: "Atélectasie et complications respiratoires postopératoires",
      definition: "Réduction de l'aération d'une partie du poumon après chirurgie, favorisée par anesthésie, douleur, respiration superficielle et immobilité.",
      physiopathologie: "La diminution des volumes pulmonaires et la mauvaise expansion alvéolaire entraînent un déséquilibre ventilation-perfusion et favorisent rétention de sécrétions et hypoxémie.",
      risques: "Chirurgie thoracique/abdominale, douleur, tabagisme, obésité, maladie pulmonaire, sédation et immobilité.",
      manifestations: "Tachypnée, baisse de saturation, diminution des bruits respiratoires, respiration superficielle et parfois crépitants ou dyspnée.",
      examens: "Évaluation clinique et saturation; radiographie si symptômes persistants, sévères ou diagnostic incertain.",
      traitement: "Analgésie adaptée, mobilisation, expansion pulmonaire, traitement des sécrétions et oxygène si indiqué; rechercher pneumonie, EP ou pneumothorax si aggravation.",
      soins: "Encourager respiration profonde, toux soutenue, spirométrie incitative si prescrite et correctement enseignée, changements de position et mobilisation précoce; surveiller effets des opioïdes.",
      complications: "Hypoxémie, rétention de sécrétions, pneumonie et insuffisance respiratoire.",
      education: education + " Faire pratiquer les exercices respiratoires avant et après chirurgie lorsqu'ils sont indiqués.",
      points: "Une hypoxémie postopératoire ne doit pas être automatiquement attribuée à l'atélectasie; rechercher les causes graves si le tableau est brutal ou disproportionné.",
      priorite: "Si détresse ou hypoxémie importante : ABC et oxygénation d'abord, puis rechercher rapidement dépression respiratoire, aspiration, pneumothorax, EP ou autre cause grave.",
    },
    {
      nom: "Rétention urinaire postopératoire",
      definition: "Incapacité à vider suffisamment la vessie après une intervention malgré un volume urinaire accumulé.",
      physiopathologie: "Anesthésie, opioïdes, douleur, immobilité et inhibition réflexe peuvent diminuer la sensation vésicale et la contractilité du détrusor ou augmenter la résistance sphinctérienne.",
      risques: "Anesthésie rachidienne/épidurale, opioïdes, chirurgie pelvienne, âge avancé, antécédents urologiques et volumes IV importants.",
      manifestations: "Absence de miction, inconfort ou distension sus-pubienne, agitation, petites mictions fréquentes ou fuite par regorgement.",
      examens: "Évaluer heure/volume de la dernière miction, palpation et bladder scan si disponible; surveiller entrées-sorties et fonction rénale selon contexte.",
      traitement: "Mesures non invasives puis cathétérisme intermittent ou autre stratégie selon protocole et volume résiduel.",
      soins: "Favoriser intimité, position physiologique et mobilisation sûre, surveiller bilan hydrique et rechercher distension; appliquer les seuils institutionnels pour évaluation/cathétérisme.",
      complications: "Douleur, infection urinaire, surdistension et atteinte vésicale.",
      education: education + " Demander au patient de signaler inconfort ou difficulté à uriner.",
      points: "L'absence de plainte n'exclut pas une vessie très distendue après anesthésie.",
      priorite: "Devant anurie apparente, distinguer rapidement rétention, hypovolémie et atteinte rénale; évaluer vessie et perfusion plutôt que d'attendre une distension douloureuse.",
    },
    {
      nom: "Iléus postopératoire",
      definition: "Ralentissement transitoire de la motilité intestinale après chirurgie, particulièrement abdominale, pouvant retarder le transit et l'alimentation.",
      physiopathologie: "Manipulation intestinale, inflammation, réponse au stress, déséquilibres électrolytiques et opioïdes inhibent le péristaltisme.",
      risques: "Chirurgie abdominale, opioïdes, immobilité, hypokaliémie, infection et chirurgie prolongée.",
      manifestations: "Distension, nausées/vomissements, inconfort, intolérance alimentaire et retard des gaz/selles.",
      examens: "Évaluation abdominale, bilan hydrique et électrolytique; imagerie si obstruction mécanique ou complication suspectée.",
      traitement: "Correction des causes, réduction des opioïdes si possible, mobilisation, stratégie nutritionnelle et décompression nasogastrique dans certaines situations.",
      soins: "Surveiller distension, nausées/vomissements, douleur, transit, hydratation et électrolytes; respecter les consignes d'alimentation et favoriser mobilisation prescrite.",
      complications: "Déshydratation, troubles électrolytiques, aspiration, dénutrition et prolongation d'hospitalisation.",
      education: education + " Expliquer la reprise progressive de l'alimentation et l'importance de la mobilisation.",
      points: "Une douleur intense localisée, défense, fièvre ou instabilité n'est pas un simple iléus et impose de rechercher une complication abdominale.",
      priorite: "Si vomissements importants, distension croissante ou signes péritonéaux : sécuriser ABC, garder NPO selon protocole, corriger les pertes prescrites et alerter rapidement.",
    },
  ],
  references: [
    { label: "OMS — Surgical Safety Checklist", href: "https://www.who.int/teams/integrated-health-services/patient-safety/research/safe-surgery/tool-and-resources" },
    { label: "OMS — Clinical Checklists", href: "https://www.who.int/tools/clinical-checklists" },
  ],
};
