import Link from "next/link";import {notFound,redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";import {getModuleFond} from "@/lib/cours/fondements";import {getComplementFond} from "@/lib/cours/complements-fondements";export const dynamic="force-dynamic";export const revalidate=0;
const rubriques=[["definition","Définition"],["principes","Principes essentiels"],["evaluation","Évaluation infirmière"],["interventions","Interventions infirmières"],["surveillance","Surveillance et réévaluation"],["securite","Sécurité et précautions"],["education","Éducation du patient"],["complications","Risques et complications"],["points","Points clés à retenir"]] as const;
const vigilances:Record<string,string[]>={
"demarche-soins":["Toute menace des voies aériennes, de la respiration ou de la circulation prime sur la documentation de routine.","Toute détérioration aiguë impose une nouvelle évaluation et une repriorisation du plan de soins."],
securite:["Discordance d’identité, prescription inhabituelle ou allergie connue : arrêter et clarifier avant d’agir.","Réaction aiguë pendant une transfusion : arrêter la transfusion et appliquer immédiatement le protocole institutionnel."],
"hygiene-infection":["Fièvre avec hypotension, confusion, tachypnée ou aggravation rapide : suspecter un sepsis et escalader sans délai.","Exposition professionnelle au sang ou à un liquide biologique : soins immédiats du site puis protocole d’exposition sans retard."],
"soins-base":["Signes d’aspiration ou déglutition non sûre : interrompre l’alimentation orale et évaluer rapidement.","Oligurie aiguë, malaise, dyspnée ou douleur thoracique pendant les soins : arrêter le soin et réévaluer."],
"constantes-douleur":["Une tendance anormale est souvent plus importante qu’une valeur isolée.","Désaturation, hypotension, altération aiguë de l’état mental ou douleur thoracique nécessitent une évaluation immédiate."],
documentation:["Documenter des faits observables, l’heure, les interventions et la réponse du patient.","Une transmission critique doit être claire, structurée et réalisée sans délai."],
medicaments:["Avant administration : vérifier identité, médicament, dose, voie, heure, indication, allergies et paramètres requis.","Erreur ou réaction médicamenteuse suspectée : sécuriser le patient, évaluer, alerter et suivre le protocole."],
"perfusion-hydrique":["Douleur, gonflement, blanchiment, froideur ou résistance au niveau IV : arrêter la perfusion et évaluer infiltration/extravasation.","Dyspnée aiguë, crépitants ou œdèmes sous perfusion : suspecter une surcharge et réévaluer rapidement."],
prelevements:["Toujours identifier correctement le patient et l’échantillon au moment du prélèvement selon le protocole.","Résultat critique ou changement clinique associé : transmettre immédiatement à l’équipe concernée."],
"mobilite-transferts":["Patient étourdi, hypotendu ou instable : ne pas poursuivre le lever sans sécurisation et réévaluation.","Après une chute, ne pas relever automatiquement le patient avant évaluation des blessures potentielles."],
"transitions-soins":["Avant sortie ou transfert : vérifier compréhension, médicaments, signes d’alerte, suivi et continuité des soins.","Toute information critique non transmise peut compromettre la sécurité du patient."]};
function Vigilance({slug}:{slug:string}){const items=vigilances[slug]??[];if(!items.length)return null;return <section style={{background:"#fff7ed",border:"1px solid #fed7aa",borderRadius:18,padding:20,marginBottom:22}}><h2 style={{color:"#c2410c",margin:"0 0 10px"}}>Vigilances cliniques prioritaires</h2>{items.map(x=><p key={x} style={{color:"#7c2d12",lineHeight:1.7,margin:"8px 0"}}>• {x}</p>)}</section>}
export default async function Page({params}:{params:Promise<{module:string}>}){const supabase=await createClient();const {data}=await supabase.auth.getClaims();if(!data?.claims?.sub)redirect("/connexion");const {module:slug}=await params;const module=getModuleFond(slug)??getComplementFond(slug);if(!module)notFound();return <main style={{maxWidth:920,margin:"0 auto",padding:"26px 18px 90px"}}><Link href="/cours-revisions" style={{color:"#2563eb",fontWeight:800}}>← Cours & Révisions</Link><header style={{margin:"18px 0 22px",background:"linear-gradient(135deg,#0f3d6e,#2563eb)",color:"white",borderRadius:22,padding:"28px 24px"}}><div style={{fontSize:13,fontWeight:800,opacity:.82}}>FONDEMENTS DES SOINS INFIRMIERS</div><h1 style={{fontSize:34,margin:"7px 0"}}>{module.titre}</h1><p style={{lineHeight:1.6,margin:0}}>Principes fondamentaux, sécurité, surveillance, confort et qualité des soins.</p></header><section style={{background:"#eff6ff",border:"1px solid #bfdbfe",borderRadius:18,padding:20,marginBottom:22}}><h2 style={{color:"#1d4ed8",margin:"0 0 8px"}}>Objectifs du module</h2><p style={{color:"#475569",lineHeight:1.7,margin:0}}>{module.objectifs}</p></section><section style={{background:"white",border:"1px solid #e5e7eb",borderRadius:18,padding:20,marginBottom:22}}><h2 style={{color:"#0b1f59"}}>Bref rappel</h2>{module.rappel.map(r=><p key={r} style={{color:"#475569",lineHeight:1.7}}>{r}</p>)}</section><Vigilance slug={slug}/><div style={{display:"grid",gap:18}}>{module.sujets.map((p,i)=><article key={p.nom} style={{background:"white",border:"1px solid #e5e7eb",borderRadius:19,overflow:"hidden"}}><div style={{background:"#1d4ed8",color:"white",padding:"17px 20px"}}><div style={{fontSize:11,fontWeight:800,opacity:.75}}>THÈME {i+1}</div><h2 style={{margin:"4px 0 0"}}>{p.nom}</h2></div><div style={{padding:"8px 20px 18px"}}>{rubriques.map(([k,l])=><section key={k} style={{padding:"13px 0",borderBottom:k==="points"?"none":"1px solid #edf1f6"}}><h3 style={{color:k==="points"?"#137a4d":"#1d4ed8",fontSize:15,margin:"0 0 6px"}}>{l}</h3><p style={{color:"#334155",lineHeight:1.68,margin:0}}>{p[k]}</p></section>)}<aside style={{background:"#eff6ff",border:"1px solid #bfdbfe",borderRadius:14,padding:14}}><strong style={{color:"#1d4ed8"}}>Priorité infirmière</strong><p style={{color:"#475569",lineHeight:1.65,margin:"6px 0 0"}}>{p.priorite}</p></aside></div></article>)}</div></main>}