import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { pathologiesCardiovasculaires, type PathologieCardiovasculaire } from "@/lib/cours/cardiovasculaire";

const rubriques: Array<[keyof PathologieCardiovasculaire, string]> = [
  ["definition", "Définition"],
  ["physiopathologie", "Physiopathologie"],
  ["risques", "Facteurs de risque"],
  ["manifestations", "Manifestations cliniques"],
  ["examens", "Examens diagnostiques"],
  ["traitement", "Traitement"],
  ["soins", "Prise en charge infirmière"],
  ["complications", "Complications"],
  ["education", "Éducation du patient"],
  ["points", "Points clés à retenir"],
];

const angineEnrichie: PathologieCardiovasculaire = {
  nom: "Angine de poitrine",
  definition: "L’angine de poitrine est un syndrome clinique provoqué par une ischémie myocardique transitoire : l’apport en oxygène au muscle cardiaque devient momentanément insuffisant par rapport à ses besoins, sans preuve de nécrose myocardique aiguë. Elle se manifeste le plus souvent par une gêne, une pression ou un serrement thoracique. L’angine stable suit généralement un profil prévisible, alors qu’une douleur nouvelle, plus fréquente, plus intense, plus prolongée ou survenant au repos doit faire rechercher rapidement un syndrome coronarien aigu.",
  physiopathologie: "Dans l’angine stable, une plaque athéroscléreuse réduit la réserve de débit d’une artère coronaire. Au repos, le débit peut rester suffisant, mais l’effort, le stress, la tachycardie ou une augmentation de la pression artérielle accroissent les besoins du myocarde en oxygène. Lorsque la circulation coronaire ne peut pas répondre à cette demande, une ischémie réversible apparaît et provoque les symptômes. Dans les formes instables, une modification aiguë de la plaque avec activation plaquettaire et thrombose partielle peut réduire brutalement le débit coronaire ; cette situation appartient au spectre des syndromes coronariens aigus et nécessite une évaluation urgente.",
  risques: "Les facteurs de risque sont principalement ceux de l’athérosclérose et de la maladie coronarienne : tabagisme, hypertension artérielle, dyslipidémie, diabète, surpoids ou obésité, sédentarité, maladie rénale chronique, âge et antécédents familiaux de maladie cardiovasculaire précoce. Chez une personne ayant déjà une maladie coronarienne, l’effort important, le froid, un repas copieux, le stress émotionnel, la tachycardie ou une anémie peuvent favoriser un déséquilibre entre apport et demande en oxygène et déclencher des symptômes.",
  manifestations: "Le patient décrit souvent une pression, un serrement, une lourdeur, une brûlure ou un inconfort rétrosternal plutôt qu’une douleur ponctuelle. La gêne peut irradier vers un ou les deux bras, les épaules, le cou, la mâchoire, le dos ou l’épigastre. Elle peut s’accompagner de dyspnée, sueurs, nausées, fatigue ou malaise. Dans l’angine stable, les symptômes sont généralement provoqués par un niveau d’effort relativement prévisible et s’améliorent avec le repos ou le traitement prescrit. Les personnes âgées, diabétiques ou certaines femmes peuvent présenter des symptômes moins typiques, notamment dyspnée ou fatigue sans douleur thoracique classique.",
  examens: "L’évaluation commence par une histoire précise des symptômes et des facteurs de risque, un examen cardiovasculaire et un ECG. Lorsqu’un syndrome coronarien aigu est possible, l’ECG doit être obtenu rapidement et les troponines cardiaques sont utilisées pour rechercher une lésion myocardique. Un ECG normal au repos n’exclut pas une ischémie. Chez un patient stable, une épreuve d’effort, une imagerie de stress ou une angiographie coronaire par tomodensitométrie peut être utilisée selon le profil clinique. Une coronarographie invasive est indiquée dans certaines situations à haut risque ou lorsque la revascularisation est envisagée.",
  traitement: "Pendant un épisode compatible avec une angine stable connue, l’effort est interrompu et le patient suit le plan thérapeutique prescrit, qui peut comprendre de la nitroglycérine. Le traitement de fond vise à réduire les symptômes et le risque cardiovasculaire : contrôle des facteurs de risque, statine, traitement antiplaquettaire et médicaments antiangineux selon les indications individuelles. Les bêtabloquants, inhibiteurs calciques ou nitrates peuvent être utilisés selon le contexte. Une angioplastie avec stent ou un pontage coronarien peut être indiqué lorsque les symptômes persistent malgré un traitement approprié ou selon l’anatomie et le niveau de risque.",
  soins: "Interrompre immédiatement l’activité et installer le patient au repos. Évaluer la douleur de façon structurée : début, localisation, caractère, intensité, irradiation, durée, facteurs déclenchants et soulageants ainsi que symptômes associés. Mesurer les signes vitaux, évaluer la perfusion et la respiration, et obtenir un ECG rapidement lorsqu’un syndrome aigu est possible. Administrer les médicaments prescrits en vérifiant leurs contre-indications et surveiller la réponse clinique. Avant l’administration d’un nitrate, contrôler notamment la pression artérielle et rechercher l’utilisation récente de médicaments inhibiteurs de la phosphodiestérase-5 lorsqu’elle est pertinente, en raison du risque d’hypotension sévère. Toute modification du profil habituel de l’angine doit entraîner une escalade rapide de la prise en charge.",
  complications: "Une angine stable peut témoigner d’une maladie coronarienne significative et évoluer avec le temps. Une rupture de plaque et une thrombose peuvent transformer un tableau stable en syndrome coronarien aigu, avec risque d’infarctus du myocarde. Les complications de la maladie coronaire sous-jacente comprennent également arythmies, insuffisance cardiaque, choc cardiogénique et mort subite. Une aggravation récente des symptômes ne doit donc pas être considérée comme une simple augmentation de l’angine habituelle sans réévaluation.",
  education: "Aider le patient à reconnaître son profil habituel de symptômes et ses facteurs déclenchants, tout en insistant sur le fait qu’un changement de ce profil constitue un signal d’alarme. Expliquer comment utiliser la nitroglycérine exactement selon la prescription et comment la conserver correctement. Renforcer l’adhésion aux traitements de prévention secondaire, l’arrêt du tabac, l’activité physique adaptée, une alimentation cardioprotectrice et le contrôle de la pression, du diabète et des lipides. Une douleur ou pression thoracique nouvelle, sévère ou persistante, surtout au repos ou accompagnée de dyspnée, sueurs, syncope ou malaise important, nécessite l’activation rapide des services d’urgence.",
  points: "L’angine correspond à une ischémie myocardique transitoire et constitue un signal de maladie coronarienne. L’angine stable présente habituellement un schéma reproductible lié à l’effort ; une douleur nouvelle, croissante, prolongée ou au repos doit faire suspecter un syndrome coronarien aigu. Un ECG normal n’exclut pas l’ischémie. Pour l’infirmier, la priorité est d’identifier rapidement les signes d’instabilité et de ne pas retarder l’évaluation urgente."
};

const infarctusEnrichi: PathologieCardiovasculaire = {
  nom: "Infarctus aigu du myocarde",
  definition: "L’infarctus aigu du myocarde (IAM) correspond à une nécrose d’une partie du muscle cardiaque provoquée par une ischémie aiguë prolongée. Dans la majorité des cas, une plaque d’athérome coronaire se rompt ou s’érode, déclenchant la formation d’un thrombus qui réduit fortement ou interrompt le flux sanguin. L’IAM fait partie des syndromes coronariens aigus et constitue une urgence vitale : plus la reperfusion est tardive, plus la quantité de myocarde définitivement lésée peut être importante.",
  physiopathologie: "Après rupture ou érosion d’une plaque, les plaquettes s’activent et un thrombus se forme dans l’artère coronaire. La réduction du débit provoque d’abord une ischémie réversible, puis une lésion cellulaire irréversible lorsque l’occlusion persiste. L’étendue de la nécrose dépend notamment de l’artère atteinte, de la durée de l’occlusion, de la circulation collatérale et des besoins métaboliques du myocarde. Un infarctus avec sus-décalage persistant du segment ST évoque généralement une occlusion coronaire aiguë nécessitant une stratégie de reperfusion urgente, tandis qu’un infarctus sans sus-décalage peut résulter d’une obstruction partielle ou intermittente mais reste une urgence cardiovasculaire.",
  risques: "Les principaux facteurs de risque sont ceux de la maladie coronarienne : tabagisme, hypertension artérielle, dyslipidémie, diabète, âge, antécédents familiaux de maladie cardiovasculaire précoce, obésité, sédentarité et maladie rénale chronique. Un antécédent de maladie coronarienne, d’angine, de stent ou d’infarctus augmente également le risque. Certains infarctus peuvent toutefois survenir par d’autres mécanismes, notamment déséquilibre majeur entre apport et demande en oxygène, embolie coronaire, dissection coronaire spontanée ou vasospasme.",
  manifestations: "La présentation classique est une douleur, une pression, un serrement ou une lourdeur thoracique prolongée, souvent rétrosternale, pouvant irradier vers les bras, les épaules, la mâchoire, le cou, le dos ou l’épigastre. Des sueurs froides, dyspnée, nausées, vomissements, faiblesse, anxiété, pâleur, palpitations ou syncope peuvent accompagner l’épisode. Certaines personnes, notamment âgées ou diabétiques, peuvent présenter une dyspnée, une fatigue extrême, un malaise ou une confusion sans douleur thoracique typique. Toute suspicion clinique impose une évaluation urgente.",
  examens: "L’ECG 12 dérivations doit être obtenu rapidement et répété si les symptômes persistent ou évoluent. Les troponines cardiaques sont les biomarqueurs essentiels pour détecter une lésion myocardique et doivent être interprétées avec le contexte clinique et leur évolution dans le temps. L’échocardiographie peut évaluer la fonction ventriculaire et rechercher certaines complications. La coronarographie identifie la lésion responsable et permet une intervention coronaire percutanée lorsque cela est indiqué. D’autres examens biologiques évaluent notamment fonction rénale, électrolytes, glycémie, hémogramme et profil lipidique.",
  traitement: "Le traitement vise à restaurer la perfusion, limiter l’extension de la nécrose et prévenir les complications. Lorsqu’une occlusion aiguë nécessitant une reperfusion est identifiée, l’intervention coronaire percutanée est privilégiée lorsqu’elle peut être réalisée rapidement ; une fibrinolyse peut être envisagée dans certaines situations lorsque l’angioplastie n’est pas disponible dans les délais appropriés et qu’il n’existe pas de contre-indication. Le traitement peut inclure antiplaquettaires, anticoagulation, statine, nitrates, bêtabloquants ou autres agents selon le type d’infarctus, la pression artérielle, la fréquence cardiaque, le risque hémorragique et les protocoles. L’oxygène n’est pas systématique : il est utilisé lorsqu’il existe une hypoxémie ou une autre indication clinique.",
  soins: "Reconnaître immédiatement les signes d’un syndrome coronarien aigu, arrêter l’effort et organiser une prise en charge urgente. Évaluer ABC, douleur, signes vitaux, saturation, perfusion périphérique et état neurologique ; mettre en place un monitorage cardiaque et obtenir l’ECG selon le protocole. Préparer l’accès veineux, les prélèvements et les traitements prescrits sans retarder une éventuelle reperfusion. Surveiller étroitement l’apparition d’arythmies, d’hypotension, de dyspnée, de crépitants, d’altération de la conscience ou d’oligurie. Après angioplastie, surveiller le site d’abord vasculaire, les saignements, l’hématome, les pouls et la perfusion distale. Réévaluer régulièrement la douleur et la réponse aux interventions.",
  complications: "Les complications précoces comprennent arythmies ventriculaires, blocs de conduction, insuffisance cardiaque aiguë, œdème pulmonaire, choc cardiogénique et arrêt cardiaque. Des complications mécaniques peuvent survenir, notamment rupture du septum interventriculaire, rupture d’un muscle papillaire avec insuffisance mitrale aiguë ou rupture de la paroi libre. D’autres complications comprennent péricardite, thrombus ventriculaire, embolies, anévrisme ventriculaire et remodelage conduisant à une insuffisance cardiaque chronique.",
  education: "Après stabilisation, expliquer l’importance de la prévention secondaire : prise régulière des médicaments, arrêt du tabac, contrôle de la pression artérielle, du diabète et des lipides, activité physique progressive et réadaptation cardiaque selon le plan de soins. Après pose d’un stent, insister sur le fait que les antiplaquettaires prescrits ne doivent pas être interrompus sans avis spécialisé. Enseigner au patient et à sa famille à reconnaître immédiatement une récidive possible : douleur ou pression thoracique, dyspnée soudaine, sueurs froides, syncope ou malaise important, et à activer les services d’urgence plutôt que d’attendre une amélioration spontanée.",
  points: "L’infarctus du myocarde est une urgence où le temps compte : reconnaître rapidement le tableau, obtenir un ECG et organiser la reperfusion lorsque indiquée peut limiter la perte myocardique. Les troponines confirment la lésion myocardique mais ne doivent pas retarder les décisions urgentes basées sur l’ECG et l’état clinique. La surveillance infirmière vise autant la douleur que les complications potentiellement mortelles : arythmies, insuffisance cardiaque et choc."
};

const restantesEnrichies: Record<number, PathologieCardiovasculaire> = {
  4: {
    nom: "Insuffisance cardiaque",
    definition: "L’insuffisance cardiaque est un syndrome clinique dans lequel le cœur ne parvient plus à assurer un débit sanguin suffisant pour répondre aux besoins de l’organisme, ou n’y parvient qu’au prix de pressions de remplissage anormalement élevées. Elle peut concerner principalement le ventricule gauche, le ventricule droit ou les deux, et être aiguë ou chronique. La fraction d’éjection peut être réduite, préservée ou légèrement diminuée selon le mécanisme dominant.",
    physiopathologie: "Une altération de la contraction, du remplissage ou des deux réduit le volume d’éjection ou augmente les pressions intracardiaques. L’organisme active le système sympathique et le système rénine–angiotensine–aldostérone, entraînant vasoconstriction, rétention de sodium et d’eau et augmentation de la charge cardiaque. Ces mécanismes compensatoires peuvent initialement maintenir la perfusion mais favorisent à long terme le remodelage ventriculaire et la progression de la maladie. L’élévation des pressions du cœur gauche provoque une congestion pulmonaire ; l’atteinte droite favorise œdèmes périphériques et congestion veineuse systémique.",
    risques: "Les causes fréquentes comprennent hypertension artérielle, maladie coronarienne et infarctus, valvulopathies, cardiomyopathies, arythmies persistantes et diabète. La maladie rénale, l’obésité, certaines cardiopathies congénitales, toxiques ou infections myocardiques peuvent également contribuer. Chez un patient connu insuffisant cardiaque, infection, excès de sodium, mauvaise observance, arythmie, ischémie, anémie ou aggravation rénale peuvent précipiter une décompensation.",
    manifestations: "Dyspnée d’effort puis parfois au repos, orthopnée, dyspnée paroxystique nocturne, fatigue et diminution de la tolérance à l’effort sont fréquentes. La congestion pulmonaire peut donner crépitants, toux ou hypoxémie. La rétention hydrosodée peut provoquer prise de poids rapide, œdèmes déclives, turgescence jugulaire et parfois ascite. Une décompensation sévère peut s’accompagner d’hypotension, confusion, peau froide, oligurie et signes d’hypoperfusion.",
    examens: "L’évaluation comprend examen clinique, ECG et échocardiographie pour mesurer la fonction ventriculaire et rechercher une cause structurelle. Les peptides natriurétiques peuvent soutenir le diagnostic dans un contexte compatible. Radiographie thoracique, fonction rénale, électrolytes, hémogramme, glycémie, bilan thyroïdien et autres examens sont utilisés selon le contexte pour rechercher causes et complications. Une échocardiographie est particulièrement importante lors d’un nouveau diagnostic ou d’un changement clinique majeur.",
    traitement: "La prise en charge dépend du phénotype et de la cause. Les diurétiques sont utilisés pour soulager la congestion. Dans l’insuffisance cardiaque à fraction d’éjection réduite, plusieurs classes médicamenteuses améliorent le pronostic selon les indications, notamment inhibiteurs du système rénine–angiotensine, bêtabloquants, antagonistes des minéralocorticoïdes et inhibiteurs SGLT2. Le contrôle de la pression, du rythme, de l’ischémie et des valvulopathies est essentiel. Certaines personnes nécessitent dispositifs implantables, resynchronisation, assistance circulatoire ou transplantation.",
    soins: "Surveiller fréquence respiratoire, saturation, dyspnée, orthopnée, crépitants, pression artérielle, fréquence et rythme cardiaques, perfusion et état mental. Peser le patient régulièrement dans des conditions comparables, suivre les entrées/sorties, l’œdème, la diurèse, la fonction rénale et les électrolytes. Administrer les diurétiques et autres traitements prescrits en évaluant la réponse et les effets indésirables. Toute aggravation respiratoire, hypotension, confusion ou baisse marquée de la diurèse doit être signalée rapidement.",
    complications: "Œdème aigu pulmonaire, arythmies, insuffisance rénale aiguë, hyponatrémie, thromboembolie, défaillance hépatique congestive et choc cardiogénique peuvent survenir. Les décompensations répétées accélèrent souvent la progression fonctionnelle et augmentent le risque d’hospitalisation et de décès.",
    education: "Expliquer l’importance de la prise régulière des médicaments et du suivi. Apprendre au patient à surveiller son poids selon le plan de soins et à signaler une prise de poids inhabituelle, une aggravation de la dyspnée, des œdèmes ou une baisse de tolérance à l’effort. Renforcer les recommandations individualisées concernant sodium, liquides, activité physique, arrêt du tabac et vaccinations. Le patient doit savoir quand contacter son équipe et quand rechercher une aide urgente.",
    points: "La congestion et l’hypoperfusion sont les deux grands problèmes à rechercher. Le poids, la dyspnée, l’œdème, la diurèse et la fonction rénale donnent des informations essentielles sur l’évolution. Une décompensation avec détresse respiratoire ou signes de choc exige une réponse immédiate."
  },
  5: {
    nom: "Arythmies cardiaques",
    definition: "Les arythmies cardiaques sont des anomalies de la fréquence, de la régularité, de l’origine ou de la conduction de l’activité électrique du cœur. Elles peuvent être supraventriculaires ou ventriculaires, rapides ou lentes, intermittentes ou persistantes. Leur gravité dépend du rythme lui-même, de sa durée, de la cardiopathie sous-jacente et surtout de son retentissement hémodynamique.",
    physiopathologie: "Une automaticité anormale, une activité déclenchée, un circuit de réentrée ou un trouble de conduction peut perturber l’activation électrique normale. Une tachycardie importante raccourcit le temps de remplissage ventriculaire et augmente les besoins myocardiques en oxygène ; une bradycardie sévère réduit le débit cardiaque. Certaines arythmies, notamment la fibrillation auriculaire, favorisent la stase sanguine et le risque thromboembolique, tandis que tachycardie ventriculaire et fibrillation ventriculaire peuvent entraîner un arrêt circulatoire.",
    risques: "Cardiopathie ischémique, infarctus, insuffisance cardiaque, cardiomyopathie, valvulopathie, troubles du potassium ou du magnésium, hypoxie, médicaments pro-arythmiques, alcool ou stimulants, hyperthyroïdie et âge peuvent augmenter le risque. Certaines arythmies sont congénitales ou liées à des voies électriques anormales.",
    manifestations: "Palpitations, sensation de battements irréguliers, fatigue, étourdissements, présyncope ou syncope sont fréquents. Une arythmie mal tolérée peut provoquer douleur thoracique, dyspnée, hypotension, confusion, peau froide ou signes de choc. Certaines arythmies restent asymptomatiques et sont découvertes à l’ECG.",
    examens: "L’ECG 12 dérivations est central. Le monitorage continu, Holter, patch ou enregistreur prolongé permettent d’identifier des épisodes intermittents. Les bilans recherchent notamment anomalies électrolytiques, fonction thyroïdienne, ischémie ou autres causes réversibles. Une échocardiographie évalue la structure cardiaque lorsque nécessaire. L’étude électrophysiologique est utilisée dans certaines arythmies pour préciser le mécanisme ou guider une ablation.",
    traitement: "Le traitement dépend du rythme et de la stabilité clinique. Les causes réversibles doivent être corrigées. Une tachyarythmie instable peut nécessiter cardioversion synchronisée urgente, tandis qu’une fibrillation ventriculaire ou tachycardie ventriculaire sans pouls nécessite défibrillation et réanimation. Une bradycardie symptomatique peut nécessiter médicaments ou stimulation. Les traitements chroniques incluent contrôle de fréquence ou rythme, anticoagulation pour certaines fibrillations auriculaires et ablation ou dispositifs implantables selon indication.",
    soins: "Évaluer d’abord le patient et non seulement le moniteur : niveau de conscience, pression, pouls, douleur thoracique, respiration et perfusion. Vérifier que le rythme affiché correspond à un signal réel, obtenir un ECG lorsque possible et rechercher causes réversibles. Préparer cardioversion, défibrillation ou stimulation si l’état l’exige. Surveiller les effets des médicaments antiarythmiques et le risque hémorragique sous anticoagulants.",
    complications: "Syncope, chute du débit cardiaque, ischémie, insuffisance cardiaque, AVC embolique dans certaines arythmies auriculaires, tachycardie ventriculaire, fibrillation ventriculaire, arrêt cardiaque et mort subite sont les principales complications.",
    education: "Expliquer les symptômes d’alarme, l’importance de l’adhésion médicamenteuse et des contrôles. Enseigner la prise du pouls lorsque cela fait partie du plan de soins. Pour les patients anticoagulés, renforcer la prévention des saignements et les interactions pertinentes. Une syncope, douleur thoracique, dyspnée sévère ou palpitations accompagnées de malaise important nécessite une évaluation urgente.",
    points: "La stabilité hémodynamique guide l’urgence. Une arythmie associée à hypotension, altération mentale, douleur ischémique, détresse respiratoire ou choc doit être traitée immédiatement. Les causes réversibles, notamment électrolytes et médicaments, doivent toujours être recherchées."
  },
  6: {
    nom: "Valvulopathies",
    definition: "Les valvulopathies sont des atteintes des valves cardiaques qui provoquent soit une obstruction à l’éjection du sang, appelée sténose, soit une fuite rétrograde, appelée insuffisance ou régurgitation. Elles peuvent toucher une ou plusieurs valves et évoluer lentement pendant des années avant de provoquer des symptômes importants.",
    physiopathologie: "Une sténose impose une surcharge de pression à la cavité située en amont, entraînant hypertrophie puis parfois défaillance. Une régurgitation impose une surcharge de volume qui favorise dilatation des cavités, augmentation des pressions et congestion. Avec le temps, ces adaptations peuvent conduire à insuffisance cardiaque, hypertension pulmonaire et arythmies, notamment fibrillation auriculaire.",
    risques: "Dégénérescence calcifiée liée à l’âge, cardiopathie rhumatismale, anomalies congénitales, endocardite infectieuse, prolapsus valvulaire, atteinte ischémique d’un muscle papillaire et certaines maladies du tissu conjonctif figurent parmi les causes fréquentes selon la valve.",
    manifestations: "Souffle cardiaque, dyspnée, fatigue, diminution de la tolérance à l’effort, palpitations, douleur thoracique, syncope ou signes d’insuffisance cardiaque peuvent apparaître. Le profil dépend de la valve atteinte et du degré de sévérité. Une détérioration rapide de la dyspnée, une syncope ou un œdème pulmonaire peut annoncer une décompensation sévère.",
    examens: "L’échocardiographie avec Doppler est l’examen principal pour identifier la valve atteinte, mesurer la sévérité et évaluer les conséquences sur les cavités cardiaques. ECG, radiographie thoracique, échocardiographie transœsophagienne, scanner, IRM ou cathétérisme peuvent être utilisés selon la situation et la préparation à une intervention.",
    traitement: "La surveillance échocardiographique est suffisante pour certaines valvulopathies légères ou asymptomatiques. Les médicaments traitent surtout les conséquences comme congestion, hypertension ou arythmies. Une réparation ou un remplacement valvulaire chirurgical ou percutané devient nécessaire dans certaines formes sévères symptomatiques ou menaçant la fonction ventriculaire.",
    soins: "Surveiller dyspnée, tolérance à l’effort, poids, œdèmes, perfusion, fréquence et rythme cardiaques. Repérer toute aggravation suggérant insuffisance cardiaque ou arythmie. Autour d’une intervention valvulaire, surveiller hémodynamique, site d’accès ou plaie, saignement, rythme et signes d’infection. Renforcer l’adhésion aux anticoagulants lorsqu’ils sont prescrits pour certaines prothèses ou arythmies.",
    complications: "Insuffisance cardiaque, fibrillation auriculaire, embolies, hypertension pulmonaire, endocardite, syncope, choc et mort subite dans certaines lésions sévères sont possibles.",
    education: "Encourager le suivi cardiologique régulier, la bonne santé buccodentaire et l’observance thérapeutique. Le patient doit signaler aggravation de la dyspnée, syncope, œdème nouveau, palpitations importantes ou fièvre inexpliquée. Expliquer que la prophylaxie antibiotique avant certains gestes n’est indiquée que pour des situations cardiaques précises selon les recommandations.",
    points: "Une valvulopathie peut rester longtemps compensée. L’évolution des symptômes, de la taille des cavités et de la fonction ventriculaire est aussi importante que le souffle lui-même. Une décompensation respiratoire ou une syncope dans une valvulopathie sévère est préoccupante."
  },
  7: {
    nom: "Endocardite infectieuse",
    definition: "L’endocardite infectieuse est une infection de l’endocarde, le plus souvent localisée sur une valve native ou prothétique. Elle s’accompagne de végétations composées de micro-organismes, plaquettes et fibrine et peut détruire rapidement une valve ou provoquer des embolies systémiques.",
    physiopathologie: "Une bactériémie ou plus rarement une fongémie permet à des micro-organismes d’adhérer à une surface endocardique vulnérable. Les végétations se développent et peuvent provoquer destruction valvulaire, abcès périannulaire et insuffisance cardiaque. Des fragments peuvent se détacher et emboliser vers cerveau, rate, reins ou autres organes.",
    risques: "Prothèse valvulaire, antécédent d’endocardite, certaines cardiopathies congénitales, dispositifs intracardiaques et certaines lésions valvulaires augmentent le risque. L’usage de drogues injectables et les situations exposant à une bactériémie importante constituent d’autres facteurs selon le contexte.",
    manifestations: "Fièvre, frissons, fatigue, sueurs nocturnes, anorexie, nouveau souffle ou modification d’un souffle peuvent apparaître. Une insuffisance cardiaque, des signes neurologiques, douleurs abdominales, hématurie ou autres manifestations emboliques sont possibles. Chez certaines personnes âgées ou immunodéprimées, la fièvre peut être discrète.",
    examens: "Plusieurs séries d’hémocultures sont prélevées avant antibiothérapie lorsque la situation le permet sans retarder une urgence. L’échocardiographie transthoracique puis transœsophagienne selon la probabilité clinique recherche végétations et complications. Hémogramme, marqueurs inflammatoires, fonction rénale, analyse urinaire et imagerie ciblée complètent l’évaluation.",
    traitement: "Une antibiothérapie intraveineuse prolongée, adaptée au germe et aux sensibilités, constitue la base du traitement. Une chirurgie peut être nécessaire en cas d’insuffisance cardiaque sévère, infection non contrôlée, abcès, certaines infections de prothèse ou risque embolique élevé selon l’évaluation spécialisée.",
    soins: "Prélever correctement les hémocultures prescrites, administrer les antimicrobiens aux horaires prévus et surveiller la réponse. Évaluer température, état hémodynamique, souffle, signes d’insuffisance cardiaque, état neurologique, douleur abdominale, perfusion périphérique et fonction rénale. Surveiller les accès veineux et les effets indésirables de l’antibiothérapie prolongée.",
    complications: "Destruction valvulaire, insuffisance cardiaque aiguë, abcès cardiaque, troubles de conduction, embolie cérébrale ou systémique, atteinte rénale, sepsis et décès peuvent survenir.",
    education: "Insister sur l’importance de terminer le traitement, de maintenir une bonne hygiène buccodentaire et de signaler rapidement fièvre persistante ou nouveaux symptômes. Les patients à haut risque doivent informer leurs soignants de leur antécédent ou prothèse. La prophylaxie antibiotique n’est réservée qu’à certaines situations et doit suivre les recommandations applicables.",
    points: "Hémocultures et échocardiographie sont centrales. Fièvre persistante avec facteur de risque cardiaque, nouveau souffle, insuffisance cardiaque ou signes emboliques doit faire évoquer l’endocardite. Une dégradation hémodynamique nécessite une prise en charge urgente."
  },
  8: {
    nom: "Péricardite",
    definition: "La péricardite est une inflammation du péricarde, la membrane à deux feuillets qui entoure le cœur. Elle peut être isolée ou associée à un épanchement péricardique. La majorité des formes aiguës ont une évolution favorable, mais une accumulation importante ou rapide de liquide peut provoquer une tamponnade cardiaque.",
    physiopathologie: "L’inflammation rend les feuillets péricardiques douloureux lorsqu’ils frottent l’un contre l’autre. Une production accrue de liquide peut entraîner un épanchement. Lorsque la pression intrapéricardique augmente au point de gêner le remplissage diastolique des cavités cardiaques, le débit chute et une tamponnade peut se développer.",
    risques: "Infections virales et autres infections, maladies auto-immunes, insuffisance rénale, infarctus du myocarde, chirurgie cardiaque, traumatisme, cancer, radiothérapie et certains médicaments peuvent être en cause. Une proportion reste idiopathique.",
    manifestations: "Douleur thoracique aiguë, souvent pleurétique, aggravée en décubitus et parfois améliorée en position assise penchée vers l’avant est typique mais non constante. Un frottement péricardique peut être entendu. Fièvre légère et dyspnée sont possibles. Une hypotension, turgescence jugulaire, tachycardie, altération mentale ou dyspnée croissante peut annoncer une tamponnade.",
    examens: "ECG, échocardiographie et marqueurs inflammatoires sont fréquemment utilisés. L’échocardiographie recherche surtout un épanchement et son retentissement hémodynamique. Troponines peuvent être élevées en cas d’atteinte myocardique associée. Radiographie, scanner ou IRM peuvent compléter l’évaluation selon la cause suspectée.",
    traitement: "Le traitement dépend de la cause. Les anti-inflammatoires et la colchicine sont fréquemment utilisés dans les formes aiguës non compliquées lorsqu’ils sont appropriés. L’activité physique peut être limitée temporairement. Une tamponnade impose un drainage urgent, généralement par péricardiocentèse ou chirurgie selon le contexte.",
    soins: "Évaluer douleur, respiration, pression, fréquence cardiaque, perfusion et état mental. Installer le patient dans la position la plus confortable, souvent semi-assise. Surveiller l’apparition de signes de tamponnade et alerter immédiatement en cas d’hypotension, aggravation de la dyspnée, syncope ou baisse de perfusion. Administrer les traitements prescrits et surveiller leurs effets.",
    complications: "Épanchement péricardique important, tamponnade cardiaque, récidive et péricardite constrictive sont les principales complications.",
    education: "Expliquer la nécessité de suivre le traitement complet et de respecter les restrictions d’activité recommandées. Le patient doit consulter rapidement si la douleur ou la dyspnée s’aggrave, s’il présente syncope, malaise important ou signes de mauvaise perfusion.",
    points: "Une douleur améliorée en position penchée vers l’avant peut orienter vers une péricardite, mais toute douleur thoracique impose d’abord d’exclure les urgences coronariennes et aortiques. La tamponnade est la complication vitale à reconnaître rapidement."
  },
  9: {
    nom: "Cardiomyopathies",
    definition: "Les cardiomyopathies sont des maladies du muscle cardiaque qui altèrent sa structure et sa fonction. Les principales formes comprennent cardiomyopathie dilatée, hypertrophique et restrictive, auxquelles s’ajoutent plusieurs formes génétiques ou acquises. Elles peuvent entraîner insuffisance cardiaque, arythmies et mort subite.",
    physiopathologie: "Dans la forme dilatée, les cavités s’élargissent et la contraction systolique devient inefficace. Dans la forme hypertrophique, l’épaississement myocardique peut gêner le remplissage et parfois obstruer l’éjection du ventricule gauche. Dans la forme restrictive, la rigidité myocardique limite le remplissage diastolique. Les différentes formes peuvent favoriser augmentation des pressions, congestion, ischémie relative, arythmies et thromboembolie.",
    risques: "Mutations génétiques, antécédents familiaux, infections myocardiques, alcool et autres toxiques, médicaments cardiotoxiques, grossesse/péripartum, maladies infiltratives ou métaboliques sont des causes possibles. Chez certains patients, aucune cause précise n’est identifiée.",
    manifestations: "Dyspnée, fatigue, œdèmes, diminution de la tolérance à l’effort, douleur thoracique, palpitations, présyncope ou syncope sont fréquents. Une mort subite peut être la première manifestation dans certaines cardiomyopathies à haut risque, notamment certaines formes hypertrophiques ou arythmogènes.",
    examens: "ECG et échocardiographie sont essentiels. L’IRM cardiaque précise souvent la structure et la fibrose. Le bilan étiologique peut comprendre analyses biologiques, tests génétiques et dépistage familial. Le monitorage rythmique et les tests d’effort sont utilisés selon le risque et les symptômes.",
    traitement: "La prise en charge dépend du type. Elle peut inclure traitements de l’insuffisance cardiaque, contrôle du rythme, anticoagulation lorsqu’indiquée, limitation de certaines activités, défibrillateur implantable, stimulateur ou procédure spécialisée. Certaines formes obstructives nécessitent médicaments spécifiques ou réduction septale. Les formes avancées peuvent nécessiter assistance circulatoire ou transplantation.",
    soins: "Surveiller signes d’insuffisance cardiaque, rythme, pression, perfusion et tolérance à l’activité. Repérer syncope, palpitations soutenues, douleur thoracique ou aggravation aiguë de la dyspnée. Renforcer l’adhésion aux restrictions et traitements individualisés. Participer à l’éducation familiale lorsqu’un dépistage génétique ou cardiologique est recommandé.",
    complications: "Insuffisance cardiaque progressive, arythmies auriculaires et ventriculaires, thromboembolie, syncope, choc et mort subite sont les principales complications.",
    education: "Expliquer que les recommandations d’activité doivent être individualisées. Insister sur le suivi régulier, l’adhésion thérapeutique et le dépistage familial lorsque la maladie est héréditaire. Une syncope inexpliquée, une dyspnée nouvelle ou des palpitations prolongées doivent être signalées rapidement.",
    points: "Les cardiomyopathies ne constituent pas une maladie unique. Identifier le type, la cause et le risque rythmique est essentiel. Syncope et arythmie dans une cardiomyopathie peuvent annoncer un événement grave et ne doivent pas être banalisées."
  },
  10: {
    nom: "Artériopathie périphérique",
    definition: "L’artériopathie périphérique est le plus souvent une manifestation d’athérosclérose affectant les artères des membres inférieurs. Elle réduit progressivement la perfusion musculaire et cutanée et constitue également un marqueur important de risque cardiovasculaire systémique.",
    physiopathologie: "Le rétrécissement artériel diminue le débit sanguin. Au repos, la perfusion peut être suffisante, mais l’effort augmente les besoins musculaires et provoque une ischémie responsable de claudication. Lorsque la maladie progresse, l’apport devient insuffisant même au repos, entraînant douleur, ulcères et risque de perte tissulaire.",
    risques: "Tabagisme et diabète sont particulièrement importants. L’âge, hypertension, dyslipidémie, maladie rénale et présence d’athérosclérose coronaire ou cérébrale augmentent aussi le risque.",
    manifestations: "Claudication intermittente, douleur musculaire reproductible à la marche et soulagée par le repos, pouls diminués, peau froide, pâle ou luisante et perte de pilosité peuvent apparaître. Une douleur au repos, un ulcère non cicatrisant, une gangrène ou un membre soudainement pâle, froid et douloureux indique une ischémie sévère ou aiguë.",
    examens: "L’indice cheville-bras est un examen de première intention. L’examen clinique vasculaire, Doppler et imagerie artérielle par échographie, scanner, IRM ou angiographie sont utilisés selon la sévérité et la planification d’une revascularisation.",
    traitement: "Arrêt du tabac, exercice structuré, contrôle du diabète, de la pression et des lipides et traitements antiplaquettaires ou hypolipémiants selon indication constituent la base. Une revascularisation endovasculaire ou chirurgicale est envisagée en cas de symptômes invalidants persistants ou d’ischémie menaçant le membre.",
    soins: "Évaluer douleur, couleur, température, remplissage capillaire, pouls, sensibilité et intégrité cutanée. Comparer les deux membres. Protéger les pieds et prévenir les traumatismes, surtout chez le patient diabétique. Toute apparition aiguë de douleur intense, pâleur, froideur, paresthésie ou disparition des pouls doit entraîner une alerte immédiate.",
    complications: "Ulcères ischémiques, infection, gangrène, amputation et ischémie aiguë du membre sont possibles. Le risque d’infarctus et d’AVC est également augmenté en raison de l’athérosclérose systémique.",
    education: "Arrêt complet du tabac, marche régulière selon programme, soins quotidiens des pieds et chaussures adaptées sont essentiels. Le patient doit éviter les blessures et consulter rapidement pour toute plaie qui ne cicatrise pas ou tout changement brutal de couleur, température ou douleur du membre.",
    points: "La claudication est un signe classique mais la maladie peut être silencieuse. L’artériopathie périphérique signale aussi un risque cardiovasculaire global élevé. Une ischémie aiguë d’un membre est une urgence vasculaire."
  },
  11: {
    nom: "Thrombose veineuse profonde (TVP)",
    definition: "La thrombose veineuse profonde est la formation d’un thrombus dans une veine profonde, le plus souvent au niveau des membres inférieurs ou du bassin. Le principal danger immédiat est la migration d’une partie du thrombus vers les artères pulmonaires, provoquant une embolie pulmonaire.",
    physiopathologie: "La triade de Virchow regroupe stase veineuse, lésion endothéliale et hypercoagulabilité. Ces trois mécanismes favorisent l’activation de la coagulation et la formation d’un thrombus. Le thrombus peut s’étendre, obstruer le retour veineux ou se fragmenter et emboliser vers les poumons.",
    risques: "Immobilisation prolongée, chirurgie majeure, traumatisme, cancer, grossesse et post-partum, œstrogènes, âge, obésité, antécédent personnel de thrombose, thrombophilie, insuffisance cardiaque et certaines maladies inflammatoires augmentent le risque.",
    manifestations: "Œdème unilatéral, douleur ou sensibilité du mollet ou de la cuisse, chaleur, rougeur ou augmentation du périmètre du membre peuvent apparaître. Cependant, une TVP peut être peu symptomatique ou silencieuse. Une dyspnée brutale, douleur thoracique pleurétique, tachycardie, syncope ou hémoptysie doit faire suspecter une embolie pulmonaire.",
    examens: "La probabilité clinique guide l’utilisation des D-dimères et de l’échographie veineuse de compression. L’échographie est l’examen de référence non invasif dans la plupart des situations. Les D-dimères sont surtout utiles pour exclure une thrombose dans des contextes de faible probabilité clinique.",
    traitement: "L’anticoagulation est le traitement principal lorsqu’elle est indiquée. Le choix du médicament et la durée dépendent du contexte, du risque hémorragique, de la cause et des comorbidités. Thrombolyse, thrombectomie ou filtre cave sont réservés à des situations sélectionnées.",
    soins: "Évaluer le membre sans le masser, mesurer et documenter œdème, douleur, couleur et température. Surveiller étroitement tout signe d’embolie pulmonaire. Administrer l’anticoagulant prescrit et surveiller les signes de saignement, l’hémoglobine et les paramètres biologiques nécessaires selon le médicament. Encourager la mobilisation selon les instructions cliniques.",
    complications: "Embolie pulmonaire, récidive thromboembolique et syndrome post-thrombotique avec douleur et œdème chroniques sont les principales complications.",
    education: "Expliquer l’importance de ne pas interrompre l’anticoagulant sans avis, de signaler saignement anormal et de connaître les interactions pertinentes. Encourager mobilité, hydratation adaptée et prévention lors des périodes à risque. Dyspnée soudaine, douleur thoracique, syncope ou hémoptysie impose une aide urgente.",
    points: "Une TVP ne peut pas être confirmée ou exclue uniquement par l’examen physique. La complication à redouter est l’embolie pulmonaire. Un membre suspect ne doit pas être massé."
  },
  12: {
    nom: "Anévrisme de l’aorte",
    definition: "Un anévrisme de l’aorte est une dilatation pathologique d’un segment de l’aorte, thoracique ou abdominale. Il peut rester asymptomatique pendant longtemps. Le risque majeur est la rupture, qui provoque une hémorragie interne massive et une mortalité élevée.",
    physiopathologie: "La dégradation des fibres élastiques et du collagène affaiblit la paroi aortique. À mesure que le diamètre augmente, la tension exercée sur la paroi croît et favorise une dilatation supplémentaire. Certaines maladies génétiques du tissu conjonctif, l’athérosclérose et l’hypertension contribuent à cette fragilisation selon la localisation.",
    risques: "Âge, tabagisme, sexe masculin pour certains anévrismes abdominaux, hypertension, athérosclérose, antécédents familiaux et certaines maladies génétiques ou du tissu conjonctif sont des facteurs importants.",
    manifestations: "Beaucoup d’anévrismes sont découverts fortuitement. Un anévrisme abdominal peut provoquer douleur abdominale ou dorsale et parfois masse pulsatile. Un anévrisme thoracique peut donner douleur thoracique ou dorsale, toux, dysphagie ou enrouement. Une douleur brutale, intense et persistante associée à hypotension, syncope ou signes de choc doit faire suspecter rupture ou autre catastrophe aortique.",
    examens: "Échographie est couramment utilisée pour dépister et surveiller les anévrismes abdominaux. Le scanner angiographique fournit une évaluation précise de l’anatomie et est essentiel en urgence chez un patient suffisamment stable. IRM et échocardiographie sont utilisées dans certaines localisations et suivis.",
    traitement: "Les petits anévrismes stables peuvent être surveillés par imagerie avec contrôle des facteurs de risque, en particulier arrêt du tabac et pression artérielle. Une réparation endovasculaire ou chirurgicale est indiquée selon le diamètre, la croissance, les symptômes et la localisation. Une rupture suspectée est une urgence chirurgicale ou endovasculaire absolue.",
    soins: "Surveiller douleur, pression artérielle, fréquence cardiaque, perfusion, état mental et signes de choc. En situation aiguë, limiter les efforts, assurer un accès veineux et préparer rapidement l’imagerie ou l’intervention selon le protocole. Éviter de retarder la prise en charge par des procédures non essentielles chez un patient instable.",
    complications: "Rupture avec hémorragie massive, compression de structures adjacentes, embolisation distale, thrombose et parfois dissection selon le contexte aortique peuvent survenir.",
    education: "Insister sur arrêt du tabac, contrôle de la pression et respect des contrôles d’imagerie. Le patient doit savoir qu’une douleur thoracique, dorsale ou abdominale brutale et sévère, surtout avec malaise ou syncope, nécessite une aide urgente.",
    points: "Un anévrisme peut être silencieux jusqu’à la complication. Douleur brutale associée à hypotension ou syncope est une urgence. Le suivi régulier de la taille et de la vitesse de croissance guide la décision d’intervention."
  },
  13: {
    nom: "Choc cardiogénique",
    definition: "Le choc cardiogénique est un état de choc provoqué par une défaillance sévère de la fonction de pompe du cœur. Le débit cardiaque devient insuffisant pour maintenir la perfusion des organes malgré un volume circulant souvent adéquat. Il s’agit d’une urgence vitale associée à un risque élevé de défaillance multiviscérale.",
    physiopathologie: "La baisse du débit entraîne hypotension et hypoperfusion. L’organisme répond par activation sympathique et vasoconstriction, ce qui augmente la postcharge et peut aggraver le travail d’un cœur déjà défaillant. La pression de remplissage élevée provoque fréquemment congestion pulmonaire et hypoxémie. Une spirale s’installe : ischémie, baisse de contractilité, diminution du débit et aggravation de l’hypoperfusion.",
    risques: "Infarctus du myocarde étendu, complications mécaniques d’un infarctus, insuffisance cardiaque avancée, myocardite fulminante, cardiomyopathie sévère, arythmies graves et défaillance valvulaire aiguë peuvent provoquer un choc cardiogénique.",
    manifestations: "Hypotension, tachycardie ou parfois bradycardie, peau froide et moite, extrémités marbrées, pouls faibles, confusion, agitation, oligurie et lactate élevé traduisent l’hypoperfusion. Une dyspnée importante, crépitants et hypoxémie sont fréquents lorsque la congestion pulmonaire est présente.",
    examens: "ECG, échocardiographie rapide, troponines, lactate, gaz du sang, fonction rénale, hépatique et électrolytes aident à déterminer la cause et la gravité. La coronarographie urgente est indiquée lorsque l’infarctus est suspecté comme cause. Un monitorage hémodynamique avancé peut être utilisé dans certaines situations complexes.",
    traitement: "La prise en charge associe soutien respiratoire et circulatoire et traitement urgent de la cause. Une revascularisation rapide est essentielle lorsqu’un infarctus aigu en est responsable. Vasopresseurs et inotropes peuvent être nécessaires selon le profil hémodynamique. Une assistance circulatoire mécanique peut être envisagée dans des cas sélectionnés. Les apports liquidiens doivent être individualisés car une surcharge peut aggraver l’œdème pulmonaire.",
    soins: "Alerter immédiatement l’équipe d’urgence. Évaluer et soutenir ABC, administrer l’oxygène ou la ventilation selon indication, installer monitorage continu, obtenir accès veineux, surveiller pression, rythme, perfusion, conscience, température périphérique et diurèse. Réévaluer fréquemment la réponse aux vasopresseurs, inotropes ou interventions. Préparer sans délai la revascularisation ou l’assistance circulatoire lorsque prescrite.",
    complications: "Arrêt cardiaque, arythmies, œdème pulmonaire, insuffisance rénale aiguë, ischémie hépatique et intestinale, acidose lactique, défaillance multiviscérale et décès sont fréquents sans correction rapide.",
    education: "L’éducation est secondaire à la stabilisation. Ensuite, expliquer la maladie responsable, les traitements de prévention secondaire, la réadaptation et les signes nécessitant une consultation rapide. Le patient et sa famille doivent comprendre l’importance de reconnaître précocement une récidive de symptômes cardiaques.",
    points: "Le choc cardiogénique est une urgence vitale. Hypotension associée à signes d’hypoperfusion chez un patient cardiaque impose une escalade immédiate. Le traitement de la cause, notamment la reperfusion d’un infarctus, est aussi important que le soutien hémodynamique."
  }
};

const prioritesInfirmieres: Partial<Record<number, string>> = {
  0: "Devant une pression très élevée, évaluer immédiatement le patient et rechercher des signes d’atteinte aiguë d’organe. La gravité dépend du contexte clinique et de l’atteinte d’organe, pas uniquement du chiffre affiché sur le tensiomètre.",
  1: "Devant une douleur ou une pression thoracique nouvelle, persistante, survenant au repos ou associée à dyspnée, sueurs, nausées, malaise ou syncope, considérer d’abord un syndrome coronarien aigu. Interrompre l’effort, évaluer rapidement les signes vitaux et la perfusion, obtenir un ECG selon le protocole, maintenir une surveillance rapprochée et alerter sans retarder la prise en charge urgente.",
  2: "Devant une douleur thoracique, interrompre l’effort et déterminer immédiatement si elle correspond au profil habituel d’une angine stable ou si elle est nouvelle, plus intense, plus longue, plus fréquente ou présente au repos. En cas de changement ou de signes d’instabilité, traiter la situation comme un possible syndrome coronarien aigu : évaluation rapide, signes vitaux, ECG selon protocole, surveillance et alerte urgente.",
  3: "Devant un infarctus suspecté, la priorité est de reconnaître l’urgence et de ne pas perdre de temps : évaluer ABC et signes vitaux, mettre le patient au repos, obtenir rapidement l’ECG, installer le monitorage, préparer l’accès veineux et les traitements prescrits, puis organiser sans délai la stratégie de reperfusion lorsqu’elle est indiquée. Toute arythmie, hypotension, détresse respiratoire, altération de conscience ou signe de choc impose une escalade immédiate.",
  4: "Devant une insuffisance cardiaque, rechercher d’abord une décompensation aiguë : dyspnée au repos, hypoxémie, crépitants, hypotension, confusion, oligurie ou peau froide. Installer et surveiller le patient, évaluer respiration et perfusion, suivre poids et bilan hydrique et alerter rapidement si l’état respiratoire ou hémodynamique se détériore.",
  5: "Devant une arythmie, évaluer immédiatement la stabilité du patient avant de se concentrer sur le tracé : conscience, pression, pouls, douleur thoracique, respiration et perfusion. Une arythmie associée à hypotension, douleur ischémique, altération mentale, détresse respiratoire ou choc nécessite une intervention urgente et la préparation à cardioversion, défibrillation ou stimulation selon le rythme.",
  6: "Devant une valvulopathie, la priorité est de reconnaître la décompensation : aggravation rapide de la dyspnée, œdème pulmonaire, hypotension, syncope ou arythmie. Surveiller respiration, perfusion, rythme et signes d’insuffisance cardiaque et alerter sans délai devant une détérioration aiguë.",
  7: "Devant une endocardite suspectée, obtenir les hémocultures prescrites avant antibiothérapie lorsque cela est possible sans retarder une urgence, puis administrer les antimicrobiens à l’heure. Surveiller étroitement insuffisance cardiaque, sepsis, changement neurologique ou signes emboliques, qui peuvent annoncer une complication grave.",
  8: "Devant une péricardite, surveiller surtout l’apparition d’une tamponnade : hypotension, tachycardie, turgescence jugulaire, dyspnée croissante, syncope, confusion ou mauvaise perfusion. Toute instabilité hémodynamique impose une alerte immédiate et une préparation au drainage urgent.",
  9: "Devant une cardiomyopathie, surveiller particulièrement syncope, arythmies, aggravation de la dyspnée et signes d’hypoperfusion. Une syncope inexpliquée ou une arythmie soutenue peut annoncer un risque de mort subite et nécessite une évaluation urgente.",
  10: "Devant une artériopathie périphérique, comparer rapidement couleur, température, douleur, sensibilité et pouls des deux membres. Une douleur brutale avec pâleur, froideur, paresthésie ou disparition des pouls évoque une ischémie aiguë du membre et impose une alerte vasculaire immédiate.",
  11: "Devant une TVP suspectée, ne pas masser le membre. Surveiller surtout les signes d’embolie pulmonaire : dyspnée brutale, douleur thoracique, tachycardie, syncope ou hémoptysie. Administrer l’anticoagulation prescrite et surveiller étroitement tout saignement.",
  12: "Devant un anévrisme de l’aorte connu ou suspecté, une douleur thoracique, dorsale ou abdominale brutale associée à hypotension ou syncope doit être considérée comme une rupture potentielle. Maintenir le patient au repos, surveiller perfusion et signes vitaux, obtenir de l’aide spécialisée et préparer l’intervention urgente sans retarder la prise en charge.",
  13: "Devant un choc cardiogénique, la priorité est l’ABC et la perfusion : alerter immédiatement, monitorer en continu, soutenir oxygénation et circulation, surveiller conscience, diurèse et réponse aux traitements, puis traiter sans délai la cause, notamment organiser une reperfusion urgente si un infarctus est responsable."
};

export default async function CardiovasculairePage() {
  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  if (!data?.claims?.sub) redirect("/connexion");

  const pathologies = pathologiesCardiovasculaires.map((pathologie, index) => {
    if (index === 2) return angineEnrichie;
    if (index === 3) return infarctusEnrichi;
    if (restantesEnrichies[index]) return restantesEnrichies[index];
    return pathologie;
  });

  return (
    <main style={{ maxWidth: 920, margin: "0 auto", padding: "26px 18px 90px" }}>
      <Link href="/cours-revisions" style={{ color: "#2563eb", fontWeight: 800, fontSize: 14 }}>
        ← Cours & Révisions
      </Link>

      <header style={{ margin: "18px 0 22px", background: "linear-gradient(135deg,#071b4f,#1748b7)", color: "white", borderRadius: 22, padding: "28px 24px" }}>
        <div style={{ opacity: 0.8, fontSize: 13, fontWeight: 800 }}>SOINS INFIRMIERS MÉDICO-CHIRURGICAUX</div>
        <h1 style={{ margin: "7px 0 8px", fontSize: 34 }}>Système cardiovasculaire</h1>
        <p style={{ margin: 0, lineHeight: 1.6, opacity: 0.92 }}>
          Bref rappel anatomique et physiologique, puis étude structurée des principales pathologies cardiovasculaires.
        </p>
      </header>

      <section style={{ background: "white", border: "1px solid #e4eaf3", borderRadius: 18, padding: 22, marginBottom: 22 }}>
        <h2 style={{ color: "#0b1f59", margin: "0 0 12px", fontSize: 23 }}>Bref rappel d’anatomie et de physiologie</h2>
        <p style={{ color: "#334155", lineHeight: 1.72 }}>Le cœur est un organe musculaire à quatre cavités : oreillette droite, ventricule droit, oreillette gauche et ventricule gauche. Les valves tricuspide, pulmonaire, mitrale et aortique maintiennent normalement un flux sanguin unidirectionnel.</p>
        <p style={{ color: "#334155", lineHeight: 1.72 }}>Le cœur droit reçoit le sang veineux et l’envoie vers les poumons par la circulation pulmonaire. Le cœur gauche reçoit le sang oxygéné et le propulse dans l’aorte vers les organes par la circulation systémique. Les artères coronaires assurent l’apport sanguin au myocarde lui-même.</p>
        <p style={{ color: "#334155", lineHeight: 1.72 }}>L’activité électrique naît normalement au nœud sinusal, traverse les oreillettes, le nœud auriculo-ventriculaire puis le système His-Purkinje afin de coordonner la contraction des ventricules. Le cycle cardiaque alterne diastole, période de remplissage, et systole, période d’éjection.</p>
        <p style={{ color: "#334155", lineHeight: 1.72, marginBottom: 0 }}>Le débit cardiaque correspond au produit de la fréquence cardiaque par le volume d’éjection systolique. Une perfusion adéquate dépend donc d’une pompe efficace, d’un rythme approprié, d’un volume circulant suffisant et d’un réseau vasculaire fonctionnel.</p>
      </section>

      <div style={{ display: "grid", gap: 18 }}>
        {pathologies.map((pathologie, index) => (
          <article key={pathologie.nom} style={{ background: "white", border: "1px solid #dfe6f0", borderRadius: 19, overflow: "hidden", boxShadow: "0 6px 20px rgba(11,31,89,.05)" }}>
            <div style={{ background: "#0b1f59", color: "white", padding: "17px 20px" }}>
              <div style={{ fontSize: 11, fontWeight: 800, opacity: 0.7, letterSpacing: 0.8 }}>PATHOLOGIE {index + 1}</div>
              <h2 style={{ margin: "4px 0 0", fontSize: 22 }}>{pathologie.nom}</h2>
            </div>

            <div style={{ padding: "8px 20px 18px" }}>
              {rubriques.map(([cle, label]) => (
                <section key={String(cle)} style={{ padding: "13px 0", borderBottom: cle === "points" ? "none" : "1px solid #edf1f6" }}>
                  <h3 style={{ color: cle === "points" ? "#137a4d" : "#1748b7", fontSize: 15, margin: "0 0 6px" }}>{label}</h3>
                  <p style={{ color: "#334155", lineHeight: 1.68, margin: 0 }}>{pathologie[cle]}</p>
                </section>
              ))}

              {prioritesInfirmieres[index] && (
                <aside style={{ background: "#eef6ff", border: "1px solid #cfe3fb", borderRadius: 14, padding: 14, marginTop: 8 }}>
                  <strong style={{ color: "#0b1f59" }}>Priorité infirmière</strong>
                  <p style={{ margin: "6px 0 0", color: "#475569", lineHeight: 1.65, fontSize: 14 }}>
                    {prioritesInfirmieres[index]}
                  </p>
                </aside>
              )}
            </div>
          </article>
        ))}
      </div>

      <p style={{ marginTop: 22, color: "#718096", fontSize: 12, lineHeight: 1.55 }}>
        Contenu éducatif de révision. Les seuils diagnostiques, indications thérapeutiques et protocoles peuvent évoluer et doivent être interprétés selon les recommandations et protocoles cliniques applicables.
      </p>
    </main>
  );
}